### PR TITLE
fix: don't GC manifests

### LINKED ISSUE #4926: Garbage collector should not collect manifests
## Describe the bug

Each network upgrade has a manifest. This manifest is stored in the blockstore on start-up. The manifests are unreachable from the blockstore and will, therefore, get garbage collected. The missing manifests will cause the next network upgrade to fail.

## To reproduce

Run `forest` continuously for a week before a network upgrade.

## Log output

<details>
  <summary>Log Output</summary>
  
  ```
  2024-10-23T14:26:48.764982Z ERROR forest_filecoin::chain_sync::tipset_syncer: Syncing tipset range [2078795, 2078905] failed: Validation error: Processing error: Could not update state: manifest for network version NV24 not found in blockstore: bafy2bzaceax5zkysst7vtyup4whdxwzlpnaya3qp34rnoi6gyt4pongps7obw, Processing error: Failed to calculate state: manifest for network version NV24 not found in blockstore: bafy2bzaceax5zkysst7vtyup4whdxwzlpnaya3qp34rnoi6gyt4pongps7obw
  ```
</details>

## Expected behaviour

Manifests should not be garbage collected.

## Environment (please complete the following information):

- OS:
- Branch/commit
- Hardware

### Option 1 - Blessed column
Have a separate column for Manifest storage. Plug it into the `get` that does `DbColumn::GraphDagCborBlake2b256 | DbColumn::GraphFull` already. It's an extra read, but only when there is a miss on the above columns. 

#### Pros
1. Easy to implement
2. Clear separation of concerns in terms of storage.
#### Cons - negligible
1. A little overhead to store manifests in the db.
2. Extra read on storage miss when querying the data store, because we need to make sure that the API does not change. 

### Option 2 - Whitelist
Whitelist certain CIDs to prevent them from being GCed.

#### Pros
1. No need to add an extra column.

#### Cons
1. No separation of concerns.
2. The code gets more convoluted.
3. Extra checks for each marked record - performance degradation, though not that significant as it's just a simple "if" condition.

### Option 3 - On-demand download of manifests before network upgrades
Download bundles as needed  X epochs before the upgrade.
#### Pros
1. No permanent extra storage costs.

#### Cons
1. Lots of moving parts, more convoluted codebase.
2. Potential problems with downloads/retries.
3. Hard to test.

### PR DESCRIPTION
**Pull request by ruseinov**
## Summary of changes

Changes introduced in this pull request:

- blessed column for persistent storage

## Reference issue to close (if applicable)

Closes #4926 

## Other information and links

The actors are found fine after several GC rounds, so this is confirmed. Also, the migration now works as intended.

Manual testing:

Several GC runs prior to state migration:

```
2024-11-12T14:19:05.975826Z  INFO forest_filecoin::db::gc: filter keys for GC
2024-11-12T14:19:06.544906Z  INFO forest_filecoin::db::gc: GC sweep
2024-11-12T14:19:06.793863Z  INFO forest_filecoin::db::gc: GC finished sweep: 4189 deleted records
```

There are of course other errors that have to do with modifying the state migration epoch, but no bundle retrieval issues, I have also tested this before the `persistent` fix and it failed miserably trying to retrieve those from the DB.
```
2024-11-12T15:18:29.939559Z  INFO compute_tipset_state_blocking: forest_filecoin::state_migration: Running TukTuk migration at epoch 2136520
2024-11-12T15:18:29.985712Z  INFO forest_filecoin::chain_sync::tipset_syncer: Validating tipset: EPOCH = 2136611, N blocks = 1
2024-11-12T15:18:29.985734Z  WARN forest_filecoin::chain_sync::tipset_syncer: Got block from the future, but within clock drift threshold, 1731424710 > 1731424709
2024-11-12T15:18:29.988647Z  WARN forest_filecoin::chain_sync::tipset_syncer: Validating block [CID = bafy2bzacea3gbxtureg5u7msimtsnns2j7edqmsetgghs7uy4cxlqdnejgzgo] in EPOCH = 2136611 failed: Validation error: Processing error: Error calculating weight: Can't create a valid state tree from the given root. This error may indicate unsupported version. state_root_cid=bafy2bzaceaxzciqzroykafdbt2fcizvzphu2hex4dceseo3lzrbl6qtuy3d7u, state_root_version=unknown, Processing error: Failed to calculate state: Can't create a valid state tree from the given root. This error may indicate unsupported version. state_root_cid=bafy2bzaceaxzciqzroykafdbt2fcizvzphu2hex4dceseo3lzrbl6qtuy3d7u, state_root_version=unknown, Processing error: Could not update state: Can't create a valid state tree from the given root. This error may indicate unsupported version. state_root_cid=bafy2bzaceaxzciqzroykafdbt2fcizvzphu2hex4dceseo3lzrbl6qtuy3d7u, state_root_version=unknown, Validation error: Consensus error: Power actor not found, Consensus error: StateManager error: Can't create a valid state tree from the given root. This error may indicate unsupported version. state_root_cid=bafy2bzaceaxzciqzroykafdbt2fcizvzphu2hex4dceseo3lzrbl6qtuy3d7u, state_root_version=unknown
2024-11-12T15:18:29.988693Z  WARN forest_filecoin::chain_sync::tipset_syncer: Sync messages check state failed for single tipset
2024-11-12T15:18:29.988701Z ERROR forest_filecoin::chain_sync::tipset_syncer: Syncing tipset range [2136521, 2136611] failed: Validation error: Processing error: Error calculating weight: Can't create a valid state tree from the given root. This error may indicate unsupported version. state_root_cid=bafy2bzaceaxzciqzroykafdbt2fcizvzphu2hex4dceseo3lzrbl6qtuy3d7u, state_root_version=unknown, Processing error: Failed to calculate state: Can't create a valid state tree from the given root. This error may indicate unsupported version. state_root_cid=bafy2bzaceaxzciqzroykafdbt2fcizvzphu2hex4dceseo3lzrbl6qtuy3d7u, state_root_version=unknown, Processing error: Could not update state: Can't create a valid state tree from the given root. This error may indicate unsupported version. state_root_cid=bafy2bzaceaxzciqzroykafdbt2fcizvzphu2hex4dceseo3lzrbl6qtuy3d7u, state_root_version=unknown, Validation error: Consensus error: Power actor not found, Consensus error: StateManager error: Can't create a valid state tree from the given root. This error may indicate unsupported version. state_root_cid=bafy2bzaceaxzciqzroykafdbt2fcizvzphu2hex4dceseo3lzrbl6qtuy3d7u, state_root_version=unknown
thread 'state migration thread: 0' panicked at /Users/romanuseinov/projects/chainsafe/forest/src/state_migration/common/state_migration.rs:134:29:
failed executing job for address: t04, Reason: state migration failed for bafk2bzaceclefusmffhuuvtggrmadr3cwpwsgphtlj2wb222ztwwv5mssu5ea actor, addr t04:Serialization error for Cbor protocol: RequireLength { name: "tuple", expect: 15, value: 17 }
2024-11-12T15:18:30.090031Z  INFO forest_filecoin::state_migration::common::state_migration: Processed 100000 actors
```

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation. All new code adheres to the team's [documentation standards](https://github.com/ChainSafe/forest/wiki/Documentation-practices),
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by ruseinov** [comment]
Follow-up issue - create common helpers to use for migrations and also for DB operations.
We have to duplicate the way that the keys are being constructed in several different manners, for e.g. EthMappings and the Graph. It would be nice to share the same code that is used by the application itself to avoid human error.

**Comment by LesnyRumcajs** [comment]
Let's hold off merging and releasing until the network upgrade on the mainnet (Nov 20th) to reduce chance of potential issues.

**Review by elmattic — APPROVED** [review]

File: src/db/car/any.rs [hunk 1]
```diff
@@ -124,6 +125,19 @@ where
     }
 }
 
+impl<ReaderT> PersistentStore for AnyCar<ReaderT>
```
Comment (hanabi1224) [inline src/db/car/any.rs:128]: I feel it would be less error-prone to make `Blockstore` persistent by default and have a `GarbageCollectableStore` for storing blockchain data, what do you think?

File: src/db/gc/mod.rs [hunk 2]
```diff
@@ -473,4 +477,43 @@ mod test {
             current_epoch + 1 + depth * 2
         );
     }
+
+    #[tokio::test]
+    async fn persistent_data_resilient_to_gc() {
+        let depth = 5 as ChainEpochDelta;
+        let current_epoch = 0 as ChainEpochDelta;
+
+        let tester = GCTester::new();
```
Comment (hanabi1224) [inline src/db/gc/mod.rs:486]: Shall we test both `MemoryDB` and `ParityDB`?

File: src/daemon/mod.rs [hunk 3]
```diff
@@ -246,11 +246,7 @@ pub(super) async fn start(
         genesis_header.clone(),
     )?);
 
-    // Network Upgrade manifests are stored in the blockstore but may not be
-    // garbage collected. Until this is fixed, the GC has to be disabled.
-    // Tracking issue: https://github.com/ChainSafe/forest/issues/4926
-    // if !opts.no_gc {
-    if false {
```
Comment (hanabi1224) [inline src/daemon/mod.rs:253]: Would love to see GC being manually triggered in at least one of the CI tests.  Could you create a tracking issue if it cannot land in this PR?

Comment (ruseinov) [reply src/daemon/mod.rs:253]: there is an issue for manual gc.

File: src/db/gc/mod.rs (hunk 2 above)
Comment (ruseinov) [reply src/db/gc/mod.rs:486]: ParityDB is tricky to test, there is an issue for that. Therefore it has been tested manually.

File: src/db/car/any.rs (hunk 1 above)
Comment (ruseinov) [reply src/db/car/any.rs:128]: We can create an issue for that and we’ll address it as prioritized. It’s out of scope for this PR, I have already created an issue to generalize different stores a bit more to be able to rely on tests for different database types better.

File: src/db/gc/mod.rs (hunk 2 above)
Comment (ruseinov) [reply src/db/gc/mod.rs:486]: The main issue there is that deletes are not propagating immediately, so unit testing it reliably is not currently possible.

Comment (ruseinov) [reply src/db/gc/mod.rs:486]: actually, no issue. creating one

**Comment by ruseinov** [comment]
@hanabi1224 I've created some issues and linked others to address the comments to this PR:

1. Redesigning the DB trait structure is subject to discussion, however there is an issue here: https://github.com/ChainSafe/forest/issues/5005, feel free to add to it. I'm also looking into introducing a wrapper for MemoryDB/ParityDB in rust-f3 to have a unified interface for all kinds of storages, perhaps we could adopt that approach in forest later. When it comes to making persistent storage a default - I have my doubts about the viability of this approach just to support what is currently one niche use-case (manifest storage). 
2. Manual GC trigger issue is here: https://github.com/ChainSafe/forest/issues/4461, it's already prioritised as low as there isn't much use for it, except the CI integration testing. It will require a bit of a redesign to be able to support channels and override the automatic GC. 
3. ParityDB unit testing issue here: https://github.com/ChainSafe/forest/issues/5008, it's not trivial, I remember spending time investigating a way to manually sync all the pending transactions and it was not reliably possible at the moment. Would be great to revisit this again.

**Review by hanabi1224 — APPROVED** [review]
LGTM. It'd be great to have @lemmih making a final review as well.

**Comment by ruseinov** [comment]
> LGTM. It'd be great to have @lemmih making a final review as well.

we can do this retroactively I guess, if anything pops-up - can be fixed in the next iteration.
I’d love to tackle some of the issues linked from this PR.
