### PR TITLE
fix(deps): retire jsonrpc-v2

### LINKED ISSUE #4008: Remove `jsonrpc-v2` from `Cargo.toml`
**Issue summary**

Since we have migrated to `jsonrpsee`, we should completely remove the old `jsonrpc-v2` crate

**Other information and links**

### PR DESCRIPTION
**Pull request by hanabi1224**
## Summary of changes

Changes introduced in this pull request:

- retire `jsonrpc-v2`
- upgrade `jsonrpsee`

## Reference issue to close (if applicable)

Closes #4008, #4003

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

File: src/rpc/mod.rs [hunk 1]
```diff
@@ -284,3 +289,7 @@ where
 
     Ok(())
 }
+
+fn map_rpc_err(e: impl Display) -> RpcError {
```
Comment (elmattic) [inline src/rpc/mod.rs:293]: nit: maybe rename function to `to_rpc_err`?

**Review by elmattic — APPROVED** [review]

File: src/rpc/mod.rs (hunk 1 above)
Comment (hanabi1224) [reply src/rpc/mod.rs:293]: Fixed.

**Review by lemmih — APPROVED** [review]
