### PR TITLE
Fix cbor serialization formats and cleanup

### LINKED ISSUE #143: CBOR Encoding

### PR DESCRIPTION
**Pull request by austinabell**
**Summary of changes**
Changes introduced in this pull request:
- Implement/ fix TxMeta (or message root) serialization to tuple serialization
- Implement serialization of signed messages (will be important for signatures soon)
- Cleaned up usages of a few small things for consistency
- Adds cid function from block to access cid for block easier from header

These things were bugging me a bit and wanted to do now as we would need soon

**Reference issue to close (if applicable)**

Closes #143

**Other information and links**

### CODE REVIEW

File: blockchain/blocks/src/block.rs [hunk 1]
```diff
@@ -29,31 +29,52 @@ pub struct Block {
...
+    {
+        let (bls_messages, secp_messages) = Deserialize::deserialize(deserializer)?;
+        Ok(TxMeta {
+            bls_messages,
+            secp_messages,
+        })
+    }
+}
 
 /// ElectionPoStVerifyInfo seems to be connected to VRF
```
Comment (dutterbutter) [inline blockchain/blocks/src/block.rs]: You can also remove this struct, pretty sure its duplicated in ticket.rs

Comment (austinabell) [reply blockchain/blocks/src/block.rs]: It was duplicated in the message crate, I removed that one because it should live here and just cleaned up references to it.

Comment (dutterbutter) [reply blockchain/blocks/src/block.rs]: I am referring to `ElectionPoStVerifyInfo` sorry

Comment (austinabell) [reply blockchain/blocks/src/block.rs]: ah gotcha, unrelated to this PR but I will remove because I'm on a spree of cutting code 🔪
