### PR TITLE
fix: improve error message for EthEstimateGas and EthCall

### LINKED ISSUE #4554: feat(rpc): improve failure messages for `Filecoin.EthEstimateGas`
## Issue summary

`Lotus` uses some `Filecoin.EthCall` functionalities that have yet to be implemented in `forest` to make the failure messages more user-friendly for `Filecoin.EthEstimateGas`.  We should close the gap once `Filecoin.EthCall` is implemented
e.g. 
```
2024-07-17T14:53:44.6298673Z | Filecoin.EthEstimateGas                           | Rejected("Message has no gas limit set")                                                            | Rejected("failed to estimate gas: message execution failed: exit 33, revert reason: 0x5416eb985904247900000000000000000000000000000000000000000000000000000000, vm error: message failed with backtrace:\n00: f0131541 (method 3844450837) -- contract reverted (33)\n (RetCode=33)") |
2024-07-17T14:53:44.6304762Z | Filecoin.EthEstimateGas                           | Rejected("Message has no gas limit set")                                                            | Rejected("failed to estimate gas: message execution failed: exit 33, revert reason: none, vm error: message failed with backtrace:\n00: f0120962 (method 3844450837) -- contract reverted (33)\n (RetCode=33)")                                                                       |
2024-07-17T14:53:44.6310764Z | Filecoin.EthEstimateGas (3)                       | Rejected("Message has no gas limit set")                                                            | Rejected("failed to estimate gas: message execution failed: exit ErrUnhandledMessage(22), revert reason: none, vm error: message failed with backtrace:\n00: f017387 (method 3844450837) -- invalid method: 3844450837 (22)\n (RetCode=22)")                                          |
```

### PR DESCRIPTION
**Pull request by akaladarshi**
## Summary of changes

Changes introduced in this pull request:

- Adds `apply_message` in `eth.rs` which executes message
  - `EthEstimateGas` if the gas_estimation fails
  - `EthCall` to directly execute the message and parse the `eth` errors
 
- Adds `EthError` enum which will hold all the Ethereum errors
  - Right now only contains `ExecutionReverted`

- Adds `fn parse_eth_revert` which parses the ethereum errors (ABI encoded)

## Reference issue to close (if applicable)

Closes #4554 

## Change checklist

- [ ] I have performed a self-review of my own code,
- [ ] I have made corresponding changes to the documentation. All new code adheres to the team's [documentation standards](https://github.com/ChainSafe/forest/wiki/Documentation-practices),
- [ ] I have added tests that prove my fix is effective or that my feature works (if possible),
- [ ] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by LesnyRumcajs** [comment]
> Are we trying to achieve exact same json rpc response as of lotus? asking because Lotus uses their own go-jsonrpc library to [register](https://github.com/filecoin-project/lotus/blob/3d0018c2f023c78bafc7493a6a6138e940037da0/api/api_errors.go#L66) errors and parse them accordingly, that's why they have fine grain control over error codes and how they print, so my question

They don't have to be byte-to-byte identical, but they should be as expressive and helpful.

> Right now the code is very fragmented, we have different functions call_with_gas, call_raw, estimate_call_with_gas, ultimately all of them are trying to execute the message on top of the VM but with different configuration.

I'd love it if we have some refactoring around this. That said, it should be a separate PR.

**Comment by LesnyRumcajs** [comment]
@akaladarshi It seems some RPC regression tests are failing for `eth_call`. 

```
src/tool/subcommands/api_cmd/test_snapshot.rs:105:5:
assertion `left == right` failed
  left: Ok(String("0x0000000000000000000000000000000000000000000000000000000000002710"))
 right: Err("JSON-RPC error:\n\tcode: -32603\n\tmessage: failed to apply on state with gas: Could not load tipset state\n")
```

You can read more on those [here](https://docs.forest.chainsafe.io/developers/guides/rpc_test_snapshot). I'm happy to assist in adding a new snapshot, but we need to confirm that this result (success, whereas previously it was a failure I guess... or the other way around) is correct. Best to use https://github.com/ChainSafe/forest/blob/main/scripts/tests/api_compare/setup.sh for this (or do it locally, without docker compose) to check the results from Forest and Lotus are more or less the same.

**Comment by akaladarshi** [comment]
> without

@LesnyRumcajs Can we retry the failed CI job once more, because the error is `Could not load tipset state` (could be something db related), also we are running the `rpc_regression_tests` in make test (Unit tests/ tests) as well and it's passing in the CI.

**Comment by LesnyRumcajs** [comment]
> > without
> 
> @LesnyRumcajs Can we retry the failed CI job once more, because the error is `Could not load tipset state` (could be something db related), also we are running the `rpc_regression_tests` in make test (Unit tests/ tests) as well and it's passing in the CI.

We are not really running these in the debug mode.
https://github.com/ChainSafe/forest/blob/6cffa72ed4670c1f5aa568acd4764d756053655e/src/tool/subcommands/api_cmd/test_snapshot.rs#L187-L190

I re-triggered but I expect them to fail with the same error.

**Comment by akaladarshi** [comment]
While investigating the regression test issue, I came across interesting behaviour of current (main branch)`EthCall` implementation.

Current Forest `EthCall` Implementation is completely different from what we have in lotus.

Lotus: 
   - [EthCall](https://github.com/filecoin-project/lotus/blob/de21d03a6954e97693a24c29aca7b126bd97c666/node/impl/eth/gas.go#L239) gets the tipset based on provided block param and calls `applyMessage`
   - [applyMessage](https://github.com/filecoin-project/lotus/blob/de21d03a6954e97693a24c29aca7b126bd97c666/node/impl/eth/gas.go#L264) checks for the expensive fork and fetches the state root from the provided tipset and call `ApplyOnStateWithGas`:
     - It fetches the state & receipt CID for a given tipset by walking the chain instead of executing it (basically return the root if it exist in the store otherwise return error)
  - [ApplyOnStateWithGas](https://github.com/filecoin-project/lotus/blob/de21d03a6954e97693a24c29aca7b126bd97c666/chain/stmgr/call.go#L63): 
     - Use the provide `state root` (from above step)
     -  `execNoMessages` which means don't apply any prior messages, only apply current message
     - `checkGas` true which means convert message into it's singed message (ChainMessage)
     - Execute the signed message (ChainMessage) on top of VM by calling `ApplyMessage`
   
     
Forest:

  - [EthCall](https://github.com/ChainSafe/forest/blob/746d129c99590daf30da65c96eebfe8e65b73022/src/rpc/methods/eth.rs#L2364) gets the tipset from the provided block params and calls the `state_manager.call`
     - state manager [call](https://github.com/ChainSafe/forest/blob/746d129c99590daf30da65c96eebfe8e65b73022/src/state_manager/mod.rs#L609) fetches the heaviest tipset if not provided and calls the `call_raw`
     - [call_raw](https://github.com/ChainSafe/forest/blob/746d129c99590daf30da65c96eebfe8e65b73022/src/state_manager/mod.rs#L528):
         -  Gets the `parent state root` cid form the provided tipset
         - Execute all the prior message sent by the current message sender on top of the VM
         - calculate new sate after above step and set the new sequece
         - Apply the current message by calling [apply_implicit_message](https://github.com/ChainSafe/forest/blob/746d129c99590daf30da65c96eebfe8e65b73022/src/interpreter/vm.rs#L443) (it applies different kind of messages as compared to normal [apply_message](https://github.com/ChainSafe/forest/blob/746d129c99590daf30da65c96eebfe8e65b73022/src/interpreter/vm.rs#L466))
         

@LesnyRumcajs If you get time can you please take a look at this difference, because based on this we shouldn't be asking why regression test is failing now, instead we should be asking why it was passing earlier.

cc @elmattic  if you can share some thoughts on this it would be helpful, to get better understanding.

File: src/rpc/error.rs [hunk 1]
```diff
@@ -15,6 +16,13 @@ pub struct ServerError {
     inner: ErrorObjectOwned,
 }
 
+/// Custom error codes for the Forest node.
+pub enum ForestError {
+    /// This error indicates that the execution reverted while executing the message.
+    /// Code is taken from https://github.com/filecoin-project/lotus/blob/master/api/api_errors.go#L27
```
Comment (elmattic) [inline src/rpc/error.rs:22]: Could you provide a stable link (with a specific lotus version) to prevent code changes under the hood?

File: src/state_manager/mod.rs [hunk 2]
```diff
@@ -72,9 +74,10 @@ use rayon::prelude::ParallelBridge;
 use schemars::JsonSchema;
 use serde::{Deserialize, Serialize};
 use std::ops::RangeInclusive;
+use std::time::Duration;
 use std::{num::NonZeroUsize, sync::Arc};
 use tokio::sync::{broadcast::error::RecvError, Mutex as TokioMutex, RwLock};
-use tracing::{error, info, instrument, trace, warn};
+use tracing::{error, info, instrument, log, trace, warn};
```
Comment (elmattic) [inline src/state_manager/mod.rs:80]: You can remove unused `log` import.

File: src/rpc/methods/eth/utils.rs [hunk 3]
```diff
@@ -97,6 +100,130 @@ where
...
+                String::from("ERROR: revert reason is not cbor encoded bytes"),
+            )
+        }
+        Ok(data) => (data.clone(), parse_eth_revert(data.0.as_slice())),
+    };
+
+    (data.0, reason)
+}
+
+const ERROR_FUNCTION_SELECTOR: [u8; 4] = [0x08, 0xc3, 0x79, 0xa0]; // Error(string)
```
Comment (elmattic) [inline src/rpc/methods/eth/utils.rs:119]: Could you explain how to obtain those magic bytes?

File: src/rpc/methods/eth/utils.rs [hunk 4]
```diff
@@ -97,6 +100,130 @@ where
...
+
+/// Parse an ABI encoded revert reason from a raw return value.
+///
+/// Handles both `Error(string)` and `Panic(uint256)` formats according to
+/// Solidity's revert conventions.
+///
+/// See https://docs.soliditylang.org/en/latest/control-structures.html#panic-via-assert-and-error-via-require
+fn parse_eth_revert(data: &[u8]) -> String {
+    // If it's not long enough to contain an ABI encoded response, return immediately.
+    if data.len() < 4 + 32 {
```
Comment (elmattic) [inline src/rpc/methods/eth/utils.rs:146]: Would be better to use constants like `EVM_WORD_LENGTH`, `EVM_FUNC_SELECTOR_LENGTH`

File: src/rpc/methods/eth/utils.rs [hunk 5]
```diff
@@ -97,6 +100,130 @@ where
...
+    let selector = data.get(..4).expect("checked data length >= 4");
+
+    match selector {
+        selector if selector == PANIC_FUNCTION_SELECTOR.as_slice() => parse_panic_revert(data),
+        selector if selector == ERROR_FUNCTION_SELECTOR.as_slice() => parse_error_revert(data),
+        _ => format!("0x{}", hex::encode(data)),
+    }
+}
+
+fn parse_error_revert(data: &[u8]) -> String {
```
[the remark this answers is not in the document]
Comment (akaladarshi) [reply src/rpc/methods/eth/utils.rs:160]: I wanted to get the first round of review because this is a big change in `EthCall`, once we are satisfied I will be adding the tests.

File: src/rpc/methods/eth/utils.rs (hunk 3 above)
Comment (elmattic) [reply src/rpc/methods/eth/utils.rs:119]: Good, maybe put in the comment i.e. `... 0xa0]; // keccak256("Error(string)")`

File: CHANGELOG.md [hunk 6]
```diff
@@ -51,6 +51,7 @@ This is a mandatory release for mainnet node operators. It includes the NV25 _Te
 ### Changed
 
 - [#5452](https://github.com/ChainSafe/forest/pull/5452) Speed up void database migration.
+- [#5467](https://github.com/ChainSafe/forest/pull/5467) Improve error message for EthEstimateGas and EthCall
```
Comment (LesnyRumcajs) [inline CHANGELOG.md:54]:
```suggestion
- [#5467](https://github.com/ChainSafe/forest/pull/5467) Improve error message for `Filecoin.EthEstimateGas` and `Filecoin.EthCall`.
```

File: src/rpc/methods/eth/utils.rs
Comment (LesnyRumcajs) [inline src/rpc/methods/eth/utils.rs:1]: Let's have complete test coverage on those new methods. They are self-contained so it should be straightforward to do so.

**Review by LesnyRumcajs — COMMENTED** [review]
LGTM, other than remarks already done by @elmattic.

File: src/rpc/methods/eth/utils.rs
Comment (elmattic) [reply src/rpc/methods/eth/utils.rs:1]: It would be really helpful to have Solidity programs (in `src/tool/subcommands/api_cmd/contracts`) that produce errors, so we can call them and observe similar errors to Lotus. What do you think?

File: src/rpc/error.rs (hunk 1 above)
Comment (akaladarshi) [reply src/rpc/error.rs]: Done

File: src/state_manager/mod.rs (hunk 2 above)
Comment (akaladarshi) [reply src/state_manager/mod.rs]: Done

File: src/rpc/methods/eth/utils.rs (hunk 3 above)
Comment (akaladarshi) [reply src/rpc/methods/eth/utils.rs]: Done

File: src/rpc/methods/eth/utils.rs (hunk 4 above)
Comment (akaladarshi) [reply src/rpc/methods/eth/utils.rs]: Done.

File: src/rpc/methods/eth/utils.rs (hunk 5 above)
[the remark this answers is not in the document]
Comment (akaladarshi) [reply src/rpc/methods/eth/utils.rs:169]: Done

File: CHANGELOG.md (hunk 6 above)
Comment (akaladarshi) [reply CHANGELOG.md]: Done

File: src/rpc/methods/eth/utils.rs
Comment (akaladarshi) [reply src/rpc/methods/eth/utils.rs:1]: Should we create a separate issue for this?

**Comment by LesnyRumcajs** [comment]
The most important rule in Forest - no green checkmark in CI :heavy_check_mark:  - no review! :x: :)

File: src/rpc/methods/eth/utils.rs
Comment (LesnyRumcajs) [reply src/rpc/methods/eth/utils.rs:1]: Yeah, it's not something to tackle in this PR.

File: src/rpc/methods/eth.rs [hunk 7]
```diff
@@ -184,6 +189,30 @@ pub struct EthUint64(
 
 lotus_json_with_self!(EthUint64);
 
+impl EthUint64 {
+    pub fn from_bytes(data: &[u8]) -> Result<Self> {
+        if data.len() != EVM_WORD_LENGTH {
+            bail!("eth int must be 32 bytes");
+        }
+
+        // big indian format stores u64 in the last 8 bytes,
```
Comment (LesnyRumcajs) [inline src/rpc/methods/eth.rs:198]:
```suggestion
        // big endian format stores u64 in the last 8 bytes,
```
:)

File: src/rpc/methods/eth.rs [hunk 8]
```diff
@@ -184,6 +189,30 @@ pub struct EthUint64(
 
 lotus_json_with_self!(EthUint64);
 
+impl EthUint64 {
+    pub fn from_bytes(data: &[u8]) -> Result<Self> {
+        if data.len() != EVM_WORD_LENGTH {
+            bail!("eth int must be 32 bytes");
```
Comment (LesnyRumcajs) [inline src/rpc/methods/eth.rs:195]:
```suggestion
            bail!("eth int must be {EVM_WORD_LENGTH} bytes");
```

File: src/rpc/methods/eth.rs [hunk 9]
```diff
@@ -184,6 +189,30 @@ pub struct EthUint64(
 
 lotus_json_with_self!(EthUint64);
 
+impl EthUint64 {
+    pub fn from_bytes(data: &[u8]) -> Result<Self> {
```
Comment (LesnyRumcajs) [inline src/rpc/methods/eth.rs:193]: Do we have coverage for this method?

File: src/rpc/methods/gas.rs [hunk 10]
```diff
@@ -259,11 +258,17 @@ impl GasEstimateGasLimit {
...
     {
-        let (res, ..) = Self::estimate_call_with_gas(data, msg, tsk, VMTrace::NotTraced).await?;
+        let (res, ..) = Self::estimate_call_with_gas(data, msg, tsk, VMTrace::NotTraced)
+            .await
+            .map_err(|e| anyhow::anyhow!("gas estimation failed: {e}"))?;
         match res.msg_rct {
             Some(rct) => {
-                if rct.exit_code().value() != 0 {
-                    return Ok(-1);
+                if !rct.exit_code().is_success() {
```
Comment (LesnyRumcajs) [inline src/rpc/methods/gas.rs:266]: we could use `ensure!`

File: src/tool/subcommands/api_cmd/test_snapshots.txt [hunk 11]
```diff
@@ -18,7 +18,9 @@ filecoin_chaintipsetweight_1736937942819105.rpcsnap.json.zst
 filecoin_ethaccounts_1737446676689764.rpcsnap.json.zst
 filecoin_ethaddresstofilecoinaddress_1740132538465536.rpcsnap.json.zst
 filecoin_ethblocknumber_1741272348346171.rpcsnap.json.zst
-filecoin_ethcall_1737446676693468.rpcsnap.json.zst
+filecoin_ethcall_1744204533050503.rpcsnap.json.zst
+filecoin_ethcall_1744204533058637.rpcsnap.json.zst
+filecoin_ethcall_1744204533066529.rpcsnap.json.zst
```
Comment (LesnyRumcajs) [inline src/tool/subcommands/api_cmd/test_snapshots.txt:23]: What are the differences between each of those snapshots?

File: src/state_manager/mod.rs [hunk 12]
```diff
@@ -649,6 +652,49 @@ where
...
+                Signature::new(SignatureType::Delegated, vec![0; SECP_SIG_LEN]),
+            )),
+            _ => ChainMessage::Unsigned(msg.clone()),
+        };
+
+        let (_invoc_res, apply_ret, duration) = self
+            .call_with_gas(&mut chain_msg, &[], Some(ts), VMTrace::Traced)
+            .await?;
+        Ok(ApiInvocResult {
+            msg: msg.clone(),
```
Comment (LesnyRumcajs) [inline src/state_manager/mod.rs:688]: Is there a way to limit the number of clones for `msg` in this method?

File: src/tool/subcommands/api_cmd/test_snapshots.txt (hunk 11 above)
Comment (akaladarshi) [reply src/tool/subcommands/api_cmd/test_snapshots.txt:23]: Each one contain different `eth_calls`:
 1. No data and `to` field set to `0x0000000000000000000000000000000000000000`
 2. Contains a token transfer call to an `0x0c1d86d34e469770339b53613f3a2343accd62cb`
 3. Contract deployment call
 
 Generated from these [cases](https://github.com/ChainSafe/forest/blob/56da0ea7bb0de5a26300154113fcda71501c50b5/src/tool/subcommands/api_cmd/api_compare_tests.rs#L1208).

Comment (elmattic) [reply src/tool/subcommands/api_cmd/test_snapshots.txt:23]: As @akaladarshi mentioned, it's generated from the same API compare calls as before, just re-exported to capture the new usage of the chainstore.

File: src/state_manager/mod.rs (hunk 12 above)
Comment (akaladarshi) [reply src/state_manager/mod.rs]: Done.

File: src/rpc/methods/gas.rs (hunk 10 above)
Comment (akaladarshi) [reply src/rpc/methods/gas.rs]: Done.

File: src/rpc/methods/eth.rs (hunk 9 above)
Comment (akaladarshi) [reply src/rpc/methods/eth.rs:193]: Added more tests for this.

File: src/rpc/methods/eth.rs (hunk 8 above)
Comment (akaladarshi) [reply src/rpc/methods/eth.rs]: Done.

File: src/rpc/methods/eth.rs (hunk 7 above)
Comment (akaladarshi) [reply src/rpc/methods/eth.rs]: Done.

**Review by LesnyRumcajs — APPROVED** [review]
LGTM

**Comment by elmattic** [comment]
Hopefully Calibnet RPC checks will pass. 🐉
