### PR TITLE
drand v14 update: fix fetching around null tipsets

### LINKED ISSUE #1291: Fix drand fetching to match Lotus after NV6
**Issue summary**

The details and required work are outlined in these lotus links:

https://github.com/filecoin-project/lotus/issues/3613
https://github.com/filecoin-project/lotus/pull/7376

**Other information and links**

### PR DESCRIPTION
**Pull request by noot**
**Summary of changes**
Changes introduced in this pull request:
- implement drand changes for v14
- see https://github.com/filecoin-project/lotus/pull/7376

**Reference issue to close (if applicable)**

Closes #1291 

**Other information and links**

### CODE REVIEW

File: blockchain/state_manager/src/chain_rand.rs [hunk 1]
```diff
@@ -2,77 +2,272 @@
...
+{
+    pub fn new(
+        blks: TipsetKeys,
+        cs: Arc<ChainStore<DB>>,
+        beacon: Arc<BeaconSchedule<DrandBeacon>>,
+    ) -> Self {
+        Self { blks, cs, beacon }
+    }
+
+    /// Gets 32 bytes of randomness for ChainRand paramaterized by the DomainSeparationTag, ChainEpoch,
```
Comment (elmattic) [inline blockchain/state_manager/src/chain_rand.rs:39]: typo in _paramaterized_

File: blockchain/state_manager/src/chain_rand.rs [hunk 2]
```diff
@@ -2,77 +2,272 @@
...
+        epoch: ChainEpoch,
+    ) -> Result<BeaconEntry, Box<dyn std::error::Error>> {
+        let mut rand_ts: Arc<Tipset> = self
+            .get_beacon_randomness_tipset(blocks, epoch, false)
+            .await?;
+        let (round, _) = self.beacon.beacon_for_epoch(epoch)?;
+
+        for _ in 0..20 {
+            let cbe = rand_ts.blocks()[0].beacon_entries();
+            for v in cbe.iter() {
```
Comment (elmattic) [inline blockchain/state_manager/src/chain_rand.rs:169]: You can omit `iter()` here

File: blockchain/state_manager/src/lib.rs [hunk 3]
```diff
@@ -138,6 +154,51 @@ where
...
+    /// Entropy from the latest beacon entry.
+    pub async fn get_beacon_randomness(
+        &self,
+        blocks: &TipsetKeys,
+        pers: DomainSeparationTag,
+        round: ChainEpoch,
+        entropy: &[u8],
+    ) -> Result<[u8; 32], Box<dyn std::error::Error>> {
+        let chain_rand = ChainRand::new(blocks.to_owned(), self.cs.clone(), self.beacon.clone());
+        match self.get_network_version(round) {
```
Comment (elmattic) [inline blockchain/state_manager/src/lib.rs:167]: Would be better to match explicitly all cases of the enum instead of relying on the wildcard pattern (`_`).

Rational: if we introduce a new network version (e.g. `NetworkVersion::V15`), this would fall silently into `get_beacon_randomness_v1` which is probably not what we want. Would be better that the code do not compile and be forced to inspect and handle the new case.

File: blockchain/state_manager/src/chain_rand.rs [hunk 4]
```diff
@@ -2,77 +2,272 @@
...
+                if v.round() == round as u64 {
+                    return Ok(v.clone());
```
[the remark this answers is not in the document]
Comment (elmattic) [reply blockchain/state_manager/src/chain_rand.rs:172]: I think it's a fixed size of 32 bytes, so never mind.

File: blockchain/state_manager/src/chain_rand.rs (hunk 1 above)
Comment (noot) [reply blockchain/state_manager/src/chain_rand.rs]: fixed

File: blockchain/state_manager/src/chain_rand.rs (hunk 2 above)
Comment (noot) [reply blockchain/state_manager/src/chain_rand.rs]: updated

File: blockchain/state_manager/src/chain_rand.rs (hunk 4 above)
[the remark this answers is not in the document]
Comment (noot) [reply blockchain/state_manager/src/chain_rand.rs:172]: ok! let me know if you want me to change this, maybe there is a better way to do it

File: blockchain/state_manager/src/chain_rand.rs [hunk 5]
```diff
@@ -2,77 +2,272 @@
...
+        let ts = self.cs.tipset_from_keys(blocks).await?;
+
+        if round > ts.epoch() {
+            return Err("cannot draw randomness from the future".into());
+        }
+
+        let search_height = if round < 0 { 0 } else { round };
+
+        let res = self.cs.tipset_by_height(search_height, ts, lookback).await;
+        match res {
```
[the remark this answers is not in the document]
Comment (noot) [reply blockchain/state_manager/src/chain_rand.rs]: nice, updated!

File: blockchain/state_manager/src/lib.rs (hunk 3 above)
Comment (noot) [reply blockchain/state_manager/src/lib.rs:167]: good point, updated!

**Review by elmattic — APPROVED** [review]
