### PR TITLE
Fix block number or hash usage

### LINKED ISSUE #5125: Fix BlockNumberOrHash usage
## Describe the bug

`getTipsetByEthBlockNumberOrHash` is a function in **Lotus** used to retrieve a tipset. It accepts predefined strings such as "pending" or "latest". However, using "earliest" will result in an error.

This function is utilized in several Ethereum endpoints:

- EthGetTransactionCount
- EthGetBlockReceiptsLimited
- EthGetCode
- EthGetStorageAt
- EthGetBalance
- EthEstimateGas
- EthCall

In **Forest**, a similar function exists called `tipset_by_block_number_or_hash`. The key difference is that Forest also supports additional predefined strings such as "safe" and "finalized".

This function is used by:

- EthGetTransactionCount
- EthGetCode
- EthGetStorageAt
- EthGetBalance
- EthEstimateGas
- EthCall

And

- EthFeeHistory
- EthGetBlockByHash
- EthGetBlockByNumber
- EthGetTransactionByBlockNumberAndIndex
- EthTraceBlock

For the second list of functions, support for "safe" and "finalized" might be required. However, Forest is likely to diverge from Lotus in the first list.

To address these differences, we should:

1) **Use clear types**: Split the Predefined type into subtypes where necessary. For instance, functions like `EthGetBlockByNumber` should only accept the required subtype (e.g., a hexadecimal block number).

2) **Expand API coverage**: Ensure the API supports all possible values for predefined strings, including both accepted and rejected values, to improve robustness and compliance with the specification. This is especially important for defining a Common Node API and an OpenRPC specification.

## Environment (please complete the following information):

- OS:
- Branch/commit
- Hardware

### PR DESCRIPTION
**Pull request by sudo-shashank**
## Summary of changes

Changes introduced in this pull request:

- Introduced `ExtPredefined` which extends `Predefined` with `safe` and `finalized` predefined block.
- Changed input param to `EthHash` in `EthGetBlockByHash`
- Implemented missing case to handle `pending` in `EthGetTransactionCount`
- Added more test 

## Reference issue to close (if applicable)

Closes #5125

## Change checklist

- [X] I have performed a self-review of my own code,
- [X] I have made corresponding changes to the documentation. All new code adheres to the team's [documentation standards](https://github.com/ChainSafe/forest/wiki/Documentation-practices),
- [X] I have added tests that prove my fix is effective or that my feature works (if possible),
- [X] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

File: scripts/tests/api_compare/filter-list-offline [hunk 1]
```diff
@@ -32,3 +32,6 @@
 !Filecoin.EthGetBlockByNumber
 !eth_getBlockByNumber
 !Filecoin.ChainSetHead
+!Filecoin.EthFeeHistory
```
Comment (hanabi1224) [inline scripts/tests/api_compare/filter-list-offline:35]: Could you add some comments on why these are filtered out?

Comment (sudo-shashank) [reply scripts/tests/api_compare/filter-list-offline]: these are now removed from filter list as i have changed test type to `basic` because to compare methods that take predefined block string(like `pending`, `latest`, `safe` or `finalized`) chain head for both the comparing nodes must be in sync if not you get different tipsets to compare which will fail eventually

**Review by elmattic — CHANGES_REQUESTED** [review]

File: src/rpc/methods/eth.rs [hunk 2]
```diff
@@ -256,6 +269,8 @@ pub struct BlockHash {
 pub enum BlockNumberOrHash {
     #[schemars(with = "String")]
     PredefinedBlock(Predefined),
+    #[schemars(with = "String")]
+    ExtPredefinedBlock(ExtPredefined),
```
[the remark this answers is not in the document]
Comment (sudo-shashank) [reply src/rpc/methods/eth.rs]: fixed

File: src/rpc/methods/eth.rs [hunk 3]
```diff
@@ -1917,18 +2053,22 @@ impl RpcMethod<2> for EthGetTransactionCount {
...
         if is_evm_actor(&actor.code) {
             let evm_state = evm::State::load(ctx.store(), actor.code, actor.state)?;
             if !evm_state.is_alive() {
                 return Ok(EthUint64(0));
             }
-
             Ok(EthUint64(evm_state.nonce()))
         } else {
-            Ok(EthUint64(ctx.mpool.get_sequence(&addr)?))
+            Ok(EthUint64(actor.sequence))
```
Comment (elmattic) [inline src/rpc/methods/eth.rs:2071]: Is this a fix from previous code?

Comment (sudo-shashank) [reply src/rpc/methods/eth.rs:2071]: this is changed to match logic as per lotus code https://github.com/filecoin-project/lotus/blob/97dc1865cf1e205ed5b5f18402a4d9e8cfa29141/node/impl/eth/transaction.go#L381

File: src/tool/subcommands/api_cmd.rs [hunk 4]
```diff
@@ -2043,7 +2223,7 @@ async fn run_tests(
                         true
                     }
                     PolicyOnRejected::PassWithQuasiIdenticalError
-                        if reason_lotus.starts_with(reason_forest) =>
+                        if reason_lotus.contains(reason_forest) =>
```
Comment (elmattic) [inline src/tool/subcommands/api_cmd.rs:2226]: This may impact other tests that rely on an error string appearing at the beginning rather than elsewhere.

Comment (sudo-shashank) [reply src/tool/subcommands/api_cmd.rs:2226]: `contains` checks for the `reason_forest` to be present anywhere in `reason_lotus` should work even if `reason_lotus` starts with `reason_forest`

File: src/rpc/methods/eth.rs [hunk 5]
```diff
@@ -715,7 +793,61 @@ fn tipset_by_block_number_or_hash<DB: Blockstore>(
...
+                if walk_ts != ts {
+                    bail!("tipset is not canonical");
+                }
+            }
+            Ok(ts)
+        }
+    }
+}
+
+fn tipset_by_ext_block_number_or_hash<DB: Blockstore>(
```
[the remark this answers is not in the document]
Comment (sudo-shashank) [reply src/rpc/methods/eth.rs:865]: fixed

**Comment by LesnyRumcajs** [comment]
@elmattic @lemmih @hanabi1224

**Review by lemmih — APPROVED** [review]

**Review by hanabi1224 — APPROVED** [review]

**Review by elmattic — APPROVED** [review]
