### PR TITLE
Re-enable offline RPC check

### LINKED ISSUE #3926: Flaky Offline RPC checks.
Some endpoints timeout, others fail to pass tests: https://github.com/ChainSafe/forest/actions/runs/7741508633/job/21108978988?pr=3925

### PR DESCRIPTION
**Pull request by sudo-shashank**
## Summary of changes

Changes introduced in this pull request:

- Fix `Filecoin.StateListMessages` rpc
- Fix `Filecoin.StateMinerInfo` rpc
- Refactor how offline resources are cleaned and log
- Re-enable offline RPC CI check

| RPC Method                   | Forest | Lotus |
|------------------------------|--------|-------|
| Filecoin.StateMinerInfo (59) | Valid  | Valid |

## Reference issue to close (if applicable)

Closes #3926 

## Change checklist

- [X] I have performed a self-review of my own code,
- [X] I have made corresponding changes to the documentation,
- [X] I have added tests that prove my fix is effective or that my feature works (if possible),
- [X] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

File: src/rpc_api/data_types.rs [hunk 1]
```diff
@@ -46,11 +46,15 @@ use libipld_core::ipld::Ipld;
...
 use num_bigint::BigInt;
+use once_cell::sync::Lazy;
 use parking_lot::RwLock as SyncRwLock;
 use serde::{de, Deserialize, Deserializer, Serialize, Serializer};
 use serde_json::Value;
 use tokio::sync::RwLock;
 
+// Define a static variable for the default PeerId
+static DEFAULT_PEER_ID: Lazy<PeerId> = Lazy::new(PeerId::random);
+
```
Comment (lemmih) [inline src/rpc_api/data_types.rs:57]: Why do we need any randomness at all?

File: .github/workflows/forest.yml [hunk 2]
```diff
@@ -358,14 +358,11 @@ jobs:
...
 
           sudo chmod -R 755 $FIL_PROOFS_PARAMETER_CACHE
-  # Temporarily disabling the job as it's flaky
-  # Tracking issue: https://github.com/ChainSafe/forest/issues/3926
   offline-rpc-check:
     needs:
       - build-ubuntu
     name: Offline RPC check
     runs-on: ubuntu-latest
-    if: false
```
Comment (hanabi1224) [inline .github/workflows/forest.yml:368]: Could you manually re-run the job for, say, 10 times and make sure it's no longer flaky?

File: src/rpc_api/data_types.rs (hunk 1 above)
Comment (sudo-shashank) [reply src/rpc_api/data_types.rs]: we don't need randomness here
removed it

File: .github/workflows/forest.yml (hunk 2 above)
Comment (sudo-shashank) [reply .github/workflows/forest.yml:368]: sure

File: scripts/tests/calibnet_offline_rpc_check.sh [hunk 3]
```diff
@@ -12,6 +12,8 @@ stop_services() {
     for port in "${PORTS[@]}"; do
         fuser -k "$port/tcp" || true
     done
+    # Remove downloaded snapshot file
+    rm -rf "$snapshot"
```
Comment (LesnyRumcajs) [inline scripts/tests/calibnet_offline_rpc_check.sh:16]: It'd be great to make this function fire whenever the script is cancelled, e.g., via SIGINT. As of now, when I ran it a few times, I had lingering processes and snapshot artefacts in this directory.

File: src/rpc_api/data_types.rs [hunk 4]
```diff
@@ -46,11 +46,21 @@ use libipld_core::ipld::Ipld;
...
 use parking_lot::RwLock as SyncRwLock;
 use serde::{de, Deserialize, Deserializer, Serialize, Serializer};
 use serde_json::Value;
 use tokio::sync::RwLock;
 
+// Define a static variable for the default PeerId
+static DEFAULT_PEER_ID: Lazy<PeerId> = Lazy::new(|| {
+    let path = crate::Client::default().data_dir;
+    let keypair = crate::libp2p::keypair::get_or_create_keypair(&path)
+        .expect("Failed to create or retrieve the network keypair");
```
Comment (LesnyRumcajs) [inline src/rpc_api/data_types.rs:59]: Are you intending to use the same keypair that Forest uses normally? If so, it is under the `libp2p` directory.

https://github.com/ChainSafe/forest/blob/626fbb08603ff7c78c4ce65857da41e3d72df8fa/src/daemon/mod.rs#L157-L158

This approach won't work if the `data_dir` is changed for whatever reason, though.

Under what conditions the peer id is not present so that it needs a fallback?

Comment (lemmih) [reply src/rpc_api/data_types.rs:59]: Shashank and I discussed this in Slack and we'll try a solution that doesn't require creating any new `PeerId's.

File: src/tool/subcommands/api_cmd.rs [hunk 5]
```diff
@@ -902,7 +902,7 @@ async fn start_offline_server(
 
     // TODO: this should more be done in a script
     // Cleanup offline RPC resources
-    std::fs::remove_file(&snapshot_path)?;
+    info!("Cleaning offline RPC data directory: {:?}", db_path);
```
Comment (LesnyRumcajs) [inline src/tool/subcommands/api_cmd.rs:905]:
```suggestion
    info!("Cleaning offline RPC data directory: {}", db_path.display());
```

**Review by LesnyRumcajs — APPROVED** [review]

**Review by hanabi1224 — APPROVED** [review]
