### PR TITLE
Make event logging less verbose in steady-state mode.

### LINKED ISSUE #1456: Progress bars, and human readable logging.
**Issue summary**

Forest logging is sometimes too esoteric and not easily understood. Such logging should be better explained or removed. For example:
```
 2022-03-02T13:36:00.101Z INFO  bellperson::groth16::aggregate::verify > verify_aggregate_proof
 2022-03-02T13:36:00.101Z INFO  bellperson::groth16::aggregate::verify > verify with srs shift
 2022-03-02T13:36:00.101Z INFO  bellperson::groth16::aggregate::verify > gipa verify TIPP
 2022-03-02T13:36:00.109Z INFO  bellperson::groth16::aggregate::verify > checking aggregate pairing
 2022-03-02T13:36:00.113Z INFO  bellperson::groth16::aggregate::verify > aggregate verify done
```

Other log messages contain irrelevant data. Hashes, keys, and binary blobs of data should only be logged for debugging. Example:
```
 2022-03-02T13:36:04.152Z INFO  chain_sync::tipset_syncer              > Validating tipset: EPOCH = 1508852, KEY = [Cid("bafy2bzacecmjcvl66emmxovdbf7g6h7waxmdr4or525odyivegywt5cwxzmh6"), Cid("bafy2bzacebe7c522ypoxrnc74znqg7o6o4pw3ulxgox4hutqdgmzdyrlocf4c"), Cid("bafy2bzacedrpmehirhukukjmw53oqfdaytcemvhurdo5zrlrdu55g3ssmca24"), Cid("bafy2bzaced2chxmqfte5kcrcze627mifroe5st2lx6buk4ffn5nxm6nklgp62"), Cid("bafy2bzacea6r6bq5fxf55wz7c4eeas55hxppnzg7x5xueju76q3iuvfe7ltg6")]
```

Some warnings look exactly like errors. Can we suppress them if they are irrelevant? If they're not irrelevant, can we explain what functionality is being degraded? In any case, the warnings should not include hashes or keys. Example:
```
 2022-03-02T13:36:04.565Z WARN  chain_sync::network_context            > Failed chain_exchange response: Status InternalError: gather messages failed: failed to load msgmeta (bafy2bzacearmvzo6r2fzrj5qsl66ai6tfktl2tfmjosbb5b77xhvtddhbaeda): blockstore: block not found
```

Finally, forest does a few minutes of processing after loading a snapshot. During this time, no progress bar is shown and it is impossible to tell if forest has frozen or how long it'll take to finish. It would be nice to always have a progress bar when forest is doing intensive work.

Look into using a different logger than `pretty-env-logger`. See https://github.com/openethereum/openethereum/tree/main/bin/oe/logger.

**Other information and links**

### PR DESCRIPTION
**Pull request by lemmih**
**Summary of changes**
Changes introduced in this pull request:
- Only show tipset hashes when debug logging is enabled or when we fail to validate.
- Inhibit output from `bellperson`.

**Reference issue to close (if applicable)**

Closes #1456 

**Other information and links**

### CODE REVIEW

File: blockchain/chain_sync/src/tipset_syncer.rs [hunk 1]
```diff
@@ -1171,10 +1170,6 @@ async fn validate_tipset<
             }
         }
     }
-    info!(
```
Comment (LesnyRumcajs) [inline blockchain/chain_sync/src/tipset_syncer.rs:1174]: Isn't it worth leaving it as `debug`?

**Review by LesnyRumcajs — APPROVED** [review]

**Review by LesnyRumcajs — APPROVED** [review]

File: blockchain/chain_sync/src/tipset_syncer.rs [hunk 2]
```diff
@@ -1144,6 +1140,9 @@ async fn validate_tipset<
         validations.push(validation_fn);
     }
 
+    info!("Validating tipset: EPOCH = {}", epoch);
```
Comment (elmattic) [inline blockchain/chain_sync/src/tipset_syncer.rs:1143]: nit: using `{epoch}` for saving two keystrokes

**Review by elmattic — APPROVED** [review]
