### PR TITLE
Revive `Filecoin.EthTraceFilter` RPC

### LINKED ISSUE #5591: Filecoin.EthTraceFilter response mismatch
## Description

Latest RPC parity test failed. Please [check the logs](https://github.com/ChainSafe/forest/actions/runs/14584063545) for more information.

### PR DESCRIPTION
**Pull request by sudo-shashank**
## Summary of changes

Changes introduced in this pull request:

- Fix and enable `Filecoin.EthTraceFilter`: The issue was caused by a null tipset being resolved to the earlier available tipset, which could fall outside the specified range in the filter criteria.

## Reference issue to close (if applicable)

Closes #5591 

## Change checklist

- [X] I have performed a self-review of my own code,
- [X] I have made corresponding changes to the documentation. All new code adheres to the team's [documentation standards](https://github.com/ChainSafe/forest/wiki/Documentation-practices),
- [X] I have added tests that prove my fix is effective or that my feature works (if possible),
- [X] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

File: src/rpc/methods/eth.rs [hunk 1]
```diff
@@ -872,34 +876,57 @@ fn resolve_predefined_tipset<DB: Blockstore>(
...
+                .chain_index
+                .tipset_by_height(safe_height, head, resolve)?)
+        }
+        ExtPredefined::Finalized => {
+            let finality_height = latest_height - chain.chain_config.policy.chain_finality;
+            Ok(chain
+                .chain_index
+                .tipset_by_height(finality_height, head, resolve)?)
+        }
+        _ => unreachable!(), // All variants are already handled
```
Comment (LesnyRumcajs) [inline src/rpc/methods/eth.rs:899]: Not sure I understand - if all variants are handled, then why do we need this? If they are expected to be handled elsewhere but end up not being handled, then we should return an error and not crash the entire process.

Comment (sudo-shashank) [reply src/rpc/methods/eth.rs]: we have all the variants covered but still we should not crash if a new variant is added later and not handled
changed to return an error

Comment (hanabi1224) [reply src/rpc/methods/eth.rs]: > but to future-proof the code

Without the catch-all branch, an unhandled variant should cause a compile-time error. Why do we have to make it a runtime error?

Comment (sudo-shashank) [reply src/rpc/methods/eth.rs]: except `Safe` and `Finalized` other variants are handled separately via `resolve_predefined_tipset` this was done to reuse the code from `Predefined` in `ExtPredefined`, hence we moved from this compile time check to runtime check

**Review by LesnyRumcajs — APPROVED** [review]
Let's add a changelog entry.

**Review by hanabi1224 — APPROVED** [review]
