### PR TITLE
fix: clean and validate auxiliary state files

### LINKED ISSUE #2694: forest panics at heaviest_tipset
**Describe the bug**

Forest panics when run post `db clean` at calling `heaviest_tipset` during startup.
The file backed chain metadata info was introduced in https://github.com/ChainSafe/forest/pull/2635

context:
```
    /// Returns the currently tracked heaviest tipset.
    pub fn heaviest_tipset(&self) -> Arc<Tipset> {
        self.tipset_from_keys(self.file_backed_heaviest_tipset_keys.lock().inner())
            .expect("Failed to load heaviest tipset")
    }
```

**To Reproduce** Steps to reproduce the behavior:

1. Run `forest-cli --chain calibnet db clean`
2. Run `forest --chain calibnet --encrypt-keystore false`
3. See error

**Log output**

<details>
  <summary>Log Output</summary>
  
  
  
  ```➜  forest2 git:(main) forest --chain calibnet --encrypt-keystore false   
2023-03-21T12:06:05.680299Z  INFO forest: Using default calibnet config    
2023-03-21T12:06:05.681304Z  INFO forest::daemon: Starting Forest daemon, version 0.6.0+git.3e68aa3f    
2023-03-21T12:06:05.681409Z  INFO forest_libp2p::service: Could not decode networking keystore!    
2023-03-21T12:06:05.681867Z  INFO forest_utils::io: Permissions set to 0600 on File { fd: 9, path: "/root/.local/share/forest/libp2p/keypair", read: false, write: true }    
2023-03-21T12:06:05.682079Z  INFO forest::daemon: PeerId: 12D3KooWG5KKNqbhVQ6u3M75rXiJMwKdR8UbTdnvNWqemb5Ds4CR    
2023-03-21T12:06:05.682111Z  WARN forest::daemon: Warning: Keystore encryption disabled!    
2023-03-21T12:06:05.682291Z  INFO forest::daemon: Admin token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJBbGxvdyI6WyJyZWFkIiwid3JpdGUiLCJzaWduIiwiYWRtaW4iXSwiZXhwIjoxNjg0NTg0MzY1fQ.OTKQSVTZbNsxJ2T10u6Q_fujfmZfiktHTzcTSGIAD-Y    
2023-03-21T12:06:05.683556Z  INFO forest::daemon: Prometheus server started at 0.0.0.0:6116    
2023-03-21T12:06:05.689456Z  INFO forest_genesis: Initialized genesis: BlockHeader: Cid(bafy2bzacecyaggy24wol5ruvs6qm73gjibs2l2iyhcqmvi7r7a4ph7zx3yqd4)    
2023-03-21T12:06:05.690566Z  INFO forest::daemon: Using network :: calibnet    
thread 'main' panicked at 'Failed to load heaviest tipset: NotFound("Key for header")', /root/forest2/blockchain/chain/src/store/chain_store.rs:240:14
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[1]    3452847 IOT instruction (core dumped)  target/release/forest --chain calibnet --encrypt-keystore false
  ```
</details>

**Expected behaviour**

**Screenshots**

**Environment (please complete the following information):**

- OS:
- Rust version(e.g. `rustc --version`)
- Branch/commit: main ([3e68aa3](https://github.com/ChainSafe/forest/commit/3e68aa3f52a3a52e76c590610f7ae6c4e1af541c))

**Other information and links**

### PR DESCRIPTION
**Pull request by lemmih**
## Summary of changes

Changes introduced in this pull request:

- Validate the heaviest tipset (which is stored separately from the blockstore).
- Clean all db files when running `forest-cli db clean`.

## Reference issue to close (if applicable)

Closes #2694 

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works
      (if possible),
- [x] I have made sure the
      [CHANGELOG](https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md) is
      up-to-date. All user-facing changes should be reflected in this document.

### CODE REVIEW

File: blockchain/chain/src/store/chain_store.rs [hunk 1]
```diff
@@ -144,11 +144,19 @@ where
...
+            )?;
+            let is_valid = tipset_from_keys(&ts_cache, &db, head_store.inner()).is_ok();
+            if !is_valid {
+                // If the stored HEAD is invalid, reset it to the genesis tipset.
+                head_store.set_inner(TipsetKeys::new(vec![*genesis_block_header.cid()]))?;
+            }
+            head_store
+        });
         let file_backed_validated_blocks = Mutex::new(FileBacked::load_from_file_or_create(
             chain_data_root.join("VALIDATED_BLOCKS"),
```
Comment (creativcoder) [inline blockchain/chain/src/store/chain_store.rs:161]: can it also happen to VALIDATED_BLOCKS?

**Review by elmattic — APPROVED** [review]

**Review by creativcoder — APPROVED** [review]
