### PR TITLE
Fix `EthGetBlockReceiptsLimited`

### LINKED ISSUE #5177: `EthGetBlockReceiptsLimited` does not use limit
## Describe the bug

The bug is described here: https://github.com/filecoin-project/lotus/issues/12838

This is merely a tracking issue of the issue above, so that when the issue is resolved in Lotus, we can apply similar fix in Forest.

This way we should not differ from in `api compare` tests.

## Environment (please complete the following information):

- OS:
- Branch/commit
- Hardware

### PR DESCRIPTION
**Pull request by elmattic**
## Summary of changes

Changes introduced in this pull request:

- Fix `EthGetBlockReceiptsLimited` to properly support limit parameter

## Reference issue to close (if applicable)

Closes #5177

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation. All new code adheres to the team's [documentation standards](https://github.com/ChainSafe/forest/wiki/Documentation-practices),
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

File: src/blocks/tipset.rs [hunk 1]
```diff
@@ -90,6 +90,17 @@ impl TipsetKey {
             .collect::<Vec<_>>()
             .join(", ")
     }
+
+    /// Formats tipset key to match the Lotus display.
+    pub fn to_lotus(&self) -> String {
```
Comment (LesnyRumcajs) [inline src/blocks/tipset.rs]:
```suggestion
    pub fn format_lotus(&self) -> String {
```
nit: I'd say it's more expressive this way. `to_lotus` suggests some other type.

File: src/blocks/tipset.rs [hunk 2]
```diff
@@ -90,6 +90,17 @@ impl TipsetKey {
...
+        let s = self
+            .to_cids()
+            .into_iter()
+            .map(|cid| cid.to_string())
+            .collect::<Vec<_>>()
+            .join(",");
+        format!("{{{}}}", s)
```
Comment (LesnyRumcajs) [inline src/blocks/tipset.rs]:
```suggestion
        format!("{{{}}}", self.to_cids().into_iter().join(","))
```
Would this work? Might be a bit more efficient by avoiding intermediary `Vec` allocation

File: src/rpc/methods/eth.rs [hunk 3]
```diff
@@ -1488,14 +1488,24 @@ impl RpcMethod<2> for EthGetBlockByNumber {
...
     let ts = tipset_by_block_number_or_hash(
         ctx.chain_store(),
         block_param,
         ResolveNullTipset::TakeOlder,
     )?;
+    if let Some(limit) = limit {
+        if limit > LOOKBACK_NO_LIMIT
+            && ts.epoch() < ctx.chain_store().heaviest_tipset().epoch() - limit
+        {
+            return Err(anyhow::anyhow!(
```
Comment (LesnyRumcajs) [inline src/rpc/methods/eth.rs]: `bail!`?

Comment (elmattic) [reply src/rpc/methods/eth.rs]: Unfortunately `bail!` macro doesn't work well with `.into()`.

Comment (elmattic) [reply src/rpc/methods/eth.rs]: That said, we can change the return type of `get_block_receipts`  and then use:
```
get_block_receipts(&ctx, block_param, None)
            .await
            .map_err(|e| e.into())
```

Comment (elmattic) [reply src/rpc/methods/eth.rs]: Done.

**Review by sudo-shashank — APPROVED** [review]
