### PR TITLE
fix(rpc): Filecoin.MpoolSelect and re-enable parity tests

### LINKED ISSUE #4485: Parity test failures in Filecoin.MpoolSelect
## To reproduce

In https://github.com/ChainSafe/forest/actions/runs/9803378055/job/27069565829?pr=4455

```
# Failing request
2024-07-05T05:22:06.8798858Z Request params JSON: [[{"/":"bafy2bzaced66kabdjgpvebpp6zzwebzhefsimnfe6r4lr3bcz4lpcnplufbjm"},{"/":"bafy2bzacedfy5ualugkwto5zeth5thwtysgmziphcpiml5wya2iqzogxlyyzm"},{"/":"bafy2bzaceakfrar5hj3gu5ocdjfe2eup6abu6faeboojsdkhww2rfxr2xpijs"}],0.9]

# Result
2024-07-05T05:22:06.9320401Z | Filecoin.MpoolSelect (10)                         | Rejected("No actor state")                                                                          | Valid              
```

## Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details>

## Environment (please complete the following information):

- OS:
- Branch/commit
- Hardware

### PR DESCRIPTION
**Pull request by hanabi1224**
## Summary of changes

Changes introduced in this pull request:

- fix `Filecoin.MpoolSelect`
- re-enable parity tests

Manually verified with a previously failing case

```
     Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-07-05_height_1760963.forest.car.zst --filter MpoolSel`
| RPC Method                | Forest | Lotus |
|---------------------------|--------|-------|
| Filecoin.MpoolSelect (11) | Valid  | Valid |
```

## Reference issue to close (if applicable)

Closes #4485

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

File: src/message_pool/msg_chain.rs [hunk 1]
```diff
@@ -391,7 +391,10 @@ where
     //   limit
     // - the total gasReward cannot exceed the actor's balance; drop all messages
     //   that exceed the balance
-    let actor_state = api.get_actor_after(actor, ts)?;
+    let Ok(actor_state) = api.get_actor_after(actor, ts) else {
```
Comment (hanabi1224) [inline src/message_pool/msg_chain.rs:394]: In lotus
```go
// sanity checks:
	// - there can be no gaps in nonces, starting from the current actor nonce
	//   if there is a gap, drop messages after the gap, we can't include them
	// - all messages must have minimum gas and the total gas for the candidate messages
	//   cannot exceed the block limit; drop all messages that exceed the limit
	// - the total gasReward cannot exceed the actor's balance; drop all messages that exceed
	//   the balance
	log.Warnf("GetActorAfter: actor: %s, ts: %d", actor, ts.Height())
	a, err := mp.api.GetActorAfter(actor, ts)
	if err != nil {
		log.Errorf("failed to load actor state, not building chain for %s: %v", actor, err)
		return nil
	}
```

**Review by lemmih — APPROVED** [review]

**Review by aatifsyed — APPROVED** [review]
