### PR TITLE
Fix duplicated entries in `Filecoin.ChainGetEvents`

### LINKED ISSUE #5752: [automated] RPC parity test failure @ 19/6/25 00:50
## Description

Latest RPC parity test failed. Please [check the logs](https://github.com/ChainSafe/forest/actions/runs/15746571275) for more information.

### PR DESCRIPTION
**Pull request by elmattic**
## Summary of changes

Changes introduced in this pull request:

- Fix duplicated events

## Reference issue to close (if applicable)

Closes #5752

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation. All new code adheres to the team's [documentation standards](https://github.com/ChainSafe/forest/wiki/Documentation-practices),
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

File: src/rpc/methods/eth/filter/mod.rs [hunk 1]
```diff
@@ -369,6 +370,17 @@ impl EthEventHandler {
         tipset: &Arc<Tipset>,
         events_root: &Cid,
     ) -> anyhow::Result<Vec<Event>> {
+        fn dedup_preserving_order(items: Vec<Event>) -> Vec<Event> {
+            let mut seen = HashSet::default();
```
Comment (hanabi1224) [inline src/rpc/methods/eth/filter/mod.rs]: How about https://docs.rs/itertools/latest/itertools/trait.Itertools.html#method.unique

Comment (elmattic) [reply src/rpc/methods/eth/filter/mod.rs]: Does it preserve order?

Comment (hanabi1224) [reply src/rpc/methods/eth/filter/mod.rs]: Yes according to the doc
> returning the non-duplicate items in the order in which they occur in the adapted iterator.

Comment (hanabi1224) [reply src/rpc/methods/eth/filter/mod.rs]: And checkout https://play.rust-lang.org/?version=stable&mode=debug&edition=2024&gist=b17138bd856201f84ee556083ad7d94a

**Review by hanabi1224 — DISMISSED** [review]

**Review by hanabi1224 — DISMISSED** [review]

File: src/rpc/methods/eth/filter/mod.rs [hunk 2]
```diff
@@ -383,12 +384,13 @@ impl EthEventHandler {
...
-                let entries: Vec<crate::shim::executor::Entry> = event.event().entries();
-
-                let entries: Vec<EventEntry> = entries
+        let chain_events = filtered_events
+            .into_iter()
+            .flat_map(|events| events.into_iter())
+            .map(|event| {
+                let entries = event
+                    .event()
+                    .entries()
```
Comment (akaladarshi) [inline src/rpc/methods/eth/filter/mod.rs]: Minor suggestion: we could extract the `StampedEvent` transformation to `Event` into a separate function for readability, but the current approach works well too. Upto you

Comment (elmattic) [reply src/rpc/methods/eth/filter/mod.rs]: Good idea!

Comment (elmattic) [reply src/rpc/methods/eth/filter/mod.rs]: Done.
