### PR TITLE
[Fix] Premature end for exported snapshots

### LINKED ISSUE #3006: Snapshot files are not valid zstd archives
**Describe the bug**

**To Reproduce** Steps to reproduce the behavior:

1. Download a Forest snapshot: `forest-cli --chain calibnet snapshot fetch`
2. Verify its integrity: `zstd --test forest_snapshot_calibnet_2023-06-19_height_660943.car.zst` (this fails)
3. Forest thinks everything is okay: `forest-cli --chain calibnet snapshot validate forest_snapshot_calibnet_2023-06-19_height_660943.car.zst`

**Log output**

<details>
  <summary>Log Output</summary>
  
  ```bash
  $ zstd --test forest_snapshot_calibnet_2023-06-19_height_660943.car.zst 
eight_660943.car.zst : 2190 MB...     eight_660943.car.zst : Read error (39) : premature end

$ forest-cli --chain calibnet snapshot validate forest_snapshot_calibnet_2023-06-19_height_660943.car.zst 
✔ This will result in using approximately 1386 MB of data. Proceed? · yes
2023-06-19T06:56:25.927370Z  INFO forest_filecoin::genesis: Initialized genesis: BlockHeader: Cid(bafy2bzacecyaggy24wol5ruvs6qm73gjibs2l2iyhcqmvi7r7a4ph7zx3yqd4)    
2023-06-19T06:56:25.929039Z  INFO forest_filecoin::utils::net::download: Loading forest_snapshot_calibnet_2023-06-19_height_660943.car.zst, is_zstd_compressed: true    
280.72 MB/s 0s 2023-06-19T06:56:34.867571Z  INFO forest_filecoin::utils::db: Buffered write completed: total entries: 2577964, total size: 2.58GB, took: 8s    
Snapshot is valid

  ```
</details>

**Expected behaviour**

The `zst` snapshot files should not prematurely end.

**Screenshots**

**Environment (please complete the following information):**

- OS: Linux
- Rust version(e.g. `rustc --version`): default toolchain
- Branch/commit: latest `main`

**Other information and links**

### PR DESCRIPTION
**Pull request by ruseinov**
## Summary of changes

Changes introduced in this pull request:

- Properly close ZstdEncoder stream. 

## Reference issue to close (if applicable)

Closes #3006 

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by ruseinov** [comment]
Weirdly, this works locally like a charm, but still fails here with the same error. Perhaps this has to do with `zstd` version, though in theory it should not matter..

File: scripts/tests/calibnet_export_check.sh [hunk 1]
```diff
@@ -9,8 +9,14 @@ source "$(dirname "$0")/harness.sh"
...
 
+echo "Cleaning up the initial snapshot"
+rm -rf ./*.car.*
+
 echo "Exporting zstd compressed snapshot"
 $FOREST_CLI_PATH snapshot export
 
-echo "Verifing snapshot checksum"
+echo "Testing snapshot validity"
+zstd -t ./*.car.zst
```
Comment (lemmih) [inline scripts/tests/calibnet_export_check.sh:19]:
```suggestion
zstd --test ./*.car.zst
```

File: scripts/tests/calibnet_export_check.sh [hunk 2]
```diff
@@ -9,8 +9,14 @@ source "$(dirname "$0")/harness.sh"
...
+
+echo "Verifying snapshot checksum"
 sha256sum -c ./*.sha256sum
```
Comment (lemmih) [inline scripts/tests/calibnet_export_check.sh:22]:
```suggestion
sha256sum --check ./*.sha256sum
```

File: src/chain/store/chain_store.rs [hunk 3]
```diff
@@ -625,8 +626,26 @@ where
 
         let mut writer = writer.lock().await;
         let digest = match &mut *writer {
-            Either::Left(left) => left.get_mut().finalize().await,
-            Either::Right(right) => right.finalize().await,
+            Either::Left(left) => {
+                left.flush()
```
Comment (lemmih) [inline src/chain/store/chain_store.rs:630]: Can we define `AsyncWrite` for `Either`? Then we could just flush the `writer` instead of flushing `left` and `right`.

Comment (ruseinov) [reply src/chain/store/chain_store.rs:630]: Yeah, that would be nice and dry.
Unfortunately we'd still have to do the `finalize` separately in this case.

File: .github/workflows/forest.yml [hunk 4]
```diff
@@ -225,4 +225,4 @@ jobs:
         run: |
           chmod +x ~/.cargo/bin/forest*
       - name: Snapshot export check
-        run: ./scripts/tests/calibnet_export_check.sh
+        run:
```
Comment (lemmih) [inline .github/workflows/forest.yml:228]: Did you mean to remove this?

**Review by lemmih — APPROVED** [review]

File: .github/workflows/forest.yml (hunk 4 above)
Comment (ruseinov) [reply .github/workflows/forest.yml:228]: Nope, I think I just cut it instead of copying.

**Review by LesnyRumcajs — APPROVED** [review]

File: src/chain/store/chain_store.rs (hunk 3 above)
Comment (ruseinov) [reply src/chain/store/chain_store.rs]: I have introduced this change, turned out to be a little less involved than I thought it would.

File: src/chain/store/chain_store.rs [hunk 5]
```diff
@@ -624,6 +625,15 @@ where
...
 
         let mut writer = writer.lock().await;
+        writer
+            .flush()
+            .await
+            .map_err(|e| Error::Other(e.to_string()))?;
+        writer
+            .close()
+            .await
+            .map_err(|e| Error::Other(e.to_string()))?;
```
[the remark this answers is not in the document]
Comment (ruseinov) [reply src/chain/store/chain_store.rs:635]: To be absolutely honest we should probably handle this by having a specific error defined for each occurrence, or at least for those two. But I guess it'd be fine with `context` for now as well.
