### PR TITLE
[Fix] Implement Drop for UnorderedChainStream and handle send errors.

### LINKED ISSUE #3991: Failed to export diff snapshots
Failed to export diff snapshot on `archie` for epoch `3420000+3000`

Error: 
```
+ EPOCH_TIMESTAMP=1700996400
++ date --date=@1700996400 -u -I
+ DATE=2023-11-26
+ FILE=forest_diff_mainnet_2023-11-26_height_3420000+3000.forest.car.zst
+ test -f forest_diff_mainnet_2023-11-26_height_3420000+3000.forest.car.zst
+ /home/archie/forest-v0.16.3/forest-tool archive export --depth 3000 --epoch 3423000 --diff 3420000 --diff-depth 900 --output-path forest_diff_mainnet_2023-11-26_height_3420000+3000.forest.car.zst forest_snapshot_mainnet_2023-11-25_height_3420000.forest.car.zst forest_snapshot_mainnet_2023-12-05_height_3450000.forest.car.zst
thread 'tokio-runtime-worker' panicked at /home/runner/work/forest/forest/src/ipld/util.rs:491:42:
unreachable: ReceiveClosed
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**To Reproduce** 

Steps to reproduce the behaviour:
1. Connect to archie 
2. `cd /mnt/md0/exported`
3. Run Command: `./diff_script.sh forest_snapshot_mainnet_2023-11-25_height_3420000.forest.car.zst forest_snapshot_mainnet_2023-12-05_height_3450000.forest.car.zst`
image
Log File: `diff_export.log`

**Other information and links**
This is observed on forest version `v0.16.3` & `v0.16.6`

### PR DESCRIPTION
**Pull request by ruseinov**
## Summary of changes

Changes introduced in this pull request:

- implemented `PinnedDrop` for `UnorderedChainStream` to make sure we cleanup automatically. 
- avoid worker panics when `UnorderedChainStream` is dropped, there is no need to panic when the receiver channel is closed.
- removed redundant `join_workers` method as we are cleaning up in `Drop`. 
- improved `into_seen` implementation to work properly with `Drop` and avoiding `Arc` nuances. 

## Reference issue to close (if applicable)

Closes #3991 

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

File: src/ipld/util.rs [hunk 1]
```diff
@@ -363,18 +364,21 @@ pin_project! {
...
         fail_on_dead_links: bool,
     }
-}
 
-impl<DB, T> UnorderedChainStream<DB, T> {
-    pub fn into_seen(self) -> CidHashSet {
-        match Arc::try_unwrap(self.seen) {
-            Ok(v) => v.into_inner(),
-            Err(v) => v.lock().clone(),
+    impl<DB, T> PinnedDrop for UnorderedChainStream<DB, T> {
```
Comment (hanabi1224) [inline src/ipld/util.rs:368]: I didn't find doc for implementing `PinnedDrop` with `pin-project-lite`, have you verified `drop` is being called?

**Review by hanabi1224 — APPROVED** [review]
The change LGTM. It will be great to add some more detailed description about what is improved or fixed by this PR

File: src/ipld/util.rs (hunk 1 above)
Comment (ruseinov) [reply src/ipld/util.rs:368]: https://github.com/taiki-e/pin-project-lite/issues/61
https://github.com/taiki-e/pin-project-lite/pull/25

Comment (hanabi1224) [reply src/ipld/util.rs:368]: Thanks!

**Comment by ruseinov** [comment]
@lemmih perhaps we could also modify the `into_seen` in `ChainStream` to also use `mem::swap`?

**Comment by lemmih** [comment]
> @lemmih perhaps we could also modify the `into_seen` in `ChainStream` to also use `mem::swap`?

Sure. But I'm not sure I understand what is going on.

**Comment by ruseinov** [comment]
> > @lemmih perhaps we could also modify the `into_seen` in `ChainStream` to also use `mem::swap`?
> 
> Sure. But I'm not sure I understand what is going on.

Basically we couldn't move out of `self` due to `Drop` implementation now present, so I had to change that up for unordered implementation.

**Review by lemmih — APPROVED** [review]
