### PR TITLE
fix(rpc): update eth_tx_from_signed_eth_message to support legacy transactions

### LINKED ISSUE #4477: FIP-0091 support for Ethereum RPC methods.
## Issue summary

While consensus-critical logic was implemented in the linked PR, corresponding RPC methods still require changes.

## Other information and links

Follow-up for https://github.com/ChainSafe/forest/pull/4473

### LINKED ISSUE #4519: CI RPC parity test failures in `Filecoin.EthGetBlockByHash` and `Filecoin.EthGetBlockByNumber`
## To reproduce

1. Go to ['...'](https://github.com/ChainSafe/forest/actions/runs/9900194718/job/27350685819?pr=4517)

```
2024-07-12T00:25:01.6505221Z | Filecoin.EthGetBlockByHash                        | Rejected("signature should be 65 bytes long, but got 68 bytes")                                     | BadJson                                                                                  |
2024-07-12T00:25:01.6526008Z | Filecoin.EthGetBlockByHash                        | Rejected("signature should be 65 bytes long, but got 68 bytes")                                     | Valid                                                                                    |
2024-07-12T00:25:01.6528978Z | Filecoin.EthGetBlockByHash (18)                   | Valid                                                                                               | Valid                                                                                    |
2024-07-12T00:25:01.6531175Z | Filecoin.EthGetBlockByNumber                      | Rejected("signature should be 65 bytes long, but got 68 bytes")                                     | BadJson                                                                                  |
2024-07-12T00:25:01.6533964Z | Filecoin.EthGetBlockByNumber                      | Rejected("signature should be 65 bytes long, but got 68 bytes")                                     | Valid   
```

## Log output

<details>
  <summary>Log Output</summary>
  
  ```Paste log output here
  paste log output...
  ```
</details>

## Environment (please complete the following information):

- OS:
- Branch/commit
- Hardware

### PR DESCRIPTION
**Pull request by hanabi1224**
## Summary of changes

Changes introduced in this pull request:

- update `eth_tx_from_signed_eth_message` to support legacy transaction types namely `LEGACY_HOMESTEAD_TX` and `LEGACY_155_TX`

```
     Running `target/quick/forest-tool api compare /home/me/fr/snapshots/calibnet/forest_snapshot_calibnet_2024-07-15_height_1789837.forest.car.zst --filter EthGetBlock --n-tipsets=100`
| RPC Method                                         | Forest | Lotus |
|----------------------------------------------------|--------|-------|
| Filecoin.EthGetBlockByHash (200)                   | Valid  | Valid |
| Filecoin.EthGetBlockByNumber (200)                 | Valid  | Valid |
| Filecoin.EthGetBlockTransactionCountByHash (100)   | Valid  | Valid |
| Filecoin.EthGetBlockTransactionCountByNumber (100) | Valid  | Valid |
```

Manually verified the below payload that was failing before

```
{"jsonrpc":"2.0","id":0,"method":"Filecoin.EthGetBlockByHash","params":
 ["0x3d885d56e4ecd2be098ddbb159ba2dfc6b6756680ffeed2441062fc677efea7a",true]
}
```

## Reference issue to close (if applicable)

Closes #4519 #4518 #4477

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

File: src/rpc/methods/eth.rs [hunk 1]
```diff
@@ -1840,7 +2015,46 @@ mod test {
...
         );
-        assert_eq!(expected_hash, eth_tx_args.hash().unwrap());
+        assert_eq!(expected_hash, tx.eth_hash().unwrap());
+    }
+
+    #[test]
+    fn test_rlp_encoding_legacy() {
+        let tx = EthTx {
+            r#type: EIP_LEGACY_TX_TYPE.into(),
+            chain_id: 314159.into(),
```
Comment (LesnyRumcajs) [inline src/rpc/methods/eth.rs:2025]: Where is this test case coming from? Can we add a link to the filscan/filfox transaction?

File: src/rpc/methods/eth.rs [hunk 2]
```diff
@@ -876,7 +919,99 @@ fn recover_sig(sig: &Signature) -> Result<(EthBigInt, EthBigInt, EthBigInt)> {
         sig.bytes().get(64..65).expect("failed to get slice"),
     );
 
-    Ok((EthBigInt(r), EthBigInt(s), EthBigInt(v)))
+    Ok((r.into(), s.into(), v.into()))
+}
+
+fn recover_legacy_homestead_sig(sig: &Signature) -> Result<(EthBigInt, EthBigInt, EthBigInt)> {
```
Comment (LesnyRumcajs) [inline src/rpc/methods/eth.rs:925]: 1. Let's avoid having hard logic in the `rpc` module. This should be used for schema cosmetics and re-using existing elements. I know it's not the case for now, but avoiding adding debt here will be helpful for a future refactor.
2. This looks pretty similar to https://github.com/ChainSafe/forest/blob/07b0a8791ca3da7a07dd129d15647c344943726f/src/eth/eip_155_transaction.rs#L43 - can we avoid logic duplication?

**Review by LesnyRumcajs — CHANGES_REQUESTED** [review]

File: src/rpc/methods/eth.rs (hunk 1 above)
Comment (hanabi1224) [reply src/rpc/methods/eth.rs:2025]: Fixed.

File: src/rpc/methods/eth.rs (hunk 2 above)
Comment (hanabi1224) [reply src/rpc/methods/eth.rs]: Fixed.

**Review by lemmih — APPROVED** [review]

File: src/rpc/methods/eth/eth_tx.rs [hunk 3]
```diff
@@ -0,0 +1,196 @@
...
+pub const EIP_1559_TX_TYPE: u64 = 2;
+
+pub const ETH_LEGACY_HOMESTEAD_TX_CHAIN_ID: u64 = 0;
+
+impl ApiEthTx {
+    pub fn eth_hash(&self) -> Result<Hash> {
+        Ok(Hash(keccak(self.rlp_signed_message()?)))
+    }
+
+    pub fn rlp_signed_message(&self) -> Result<Vec<u8>> {
```
Comment (LesnyRumcajs) [inline src/rpc/methods/eth/eth_tx.rs:22]: Those seems like nitty-gritty details of Ethereum transactions. Should this live in the `eth` module?

Comment (hanabi1224) [reply src/rpc/methods/eth/eth_tx.rs]: Fixed.

File: src/eth/eip_1559_transaction.rs [hunk 4]
```diff
@@ -61,6 +61,42 @@ impl EthEip1559TxArgs {
...
+        stream.append(&self.input);
+        let access_list: &[u8] = &[];
+        stream.append_list(access_list);
+
+        stream.append(&format_bigint(&self.v)?);
+        stream.append(&format_bigint(&self.r)?);
+        stream.append(&format_bigint(&self.s)?);
+
+        let mut rlp = stream.out().to_vec();
+        rlp.insert(0, 2);
```
Comment (LesnyRumcajs) [inline src/eth/eip_1559_transaction.rs:83]: Let's comment what is this.

File: src/eth/eip_1559_transaction.rs [hunk 5]
```diff
@@ -61,6 +61,42 @@ impl EthEip1559TxArgs {
 
         Ok(self)
     }
+
+    pub fn rlp_signed_message(&self) -> anyhow::Result<Vec<u8>> {
+        let mut stream = rlp::RlpStream::new_list(12);
```
Comment (LesnyRumcajs) [inline src/eth/eip_1559_transaction.rs:66]: Is there a less scary API that doesn't require changing this number on a new field?

File: src/rpc/methods/eth/eth_tx.rs [hunk 6]
```diff
@@ -0,0 +1,123 @@
...
+
+/// Ethereum Improvement Proposals 1559 transaction type. This EIP changed Ethereum’s fee market mechanism.
+/// Transaction type can have 3 distinct values:
+/// - 0 for legacy transactions
+/// - 1 for transactions introduced in EIP-2930
+/// - 2 for transactions introduced in EIP-1559
+pub const EIP_LEGACY_TX_TYPE: u64 = 0;
+pub const EIP_1559_TX_TYPE: u64 = 2;
+
+pub const ETH_LEGACY_HOMESTEAD_TX_CHAIN_ID: u64 = 0;
```
Comment (LesnyRumcajs) [inline src/rpc/methods/eth/eth_tx.rs:15]: Let's have these constants in the `eth` module.

File: src/eth/eip_155_transaction.rs [hunk 7]
```diff
@@ -83,14 +75,42 @@ impl EthLegacyEip155TxArgs {
...
+        validate_eip155_chain_id(self.chain_id, &v)?;
 
         self.r = r;
         self.s = s;
         self.v = v;
 
         Ok(self)
     }
+
+    pub fn rlp_signed_message(&self) -> anyhow::Result<Vec<u8>> {
```
Comment (LesnyRumcajs) [inline src/eth/eip_155_transaction.rs:87]: Can we have some tests for this (and other transaction types)? Can be in a different PR. The magic number makes it scary, so I'd like to ensure this doesn't brake if someone adds a new field.

Comment (hanabi1224) [reply src/eth/eip_155_transaction.rs:87]: This has been covered by `fn test_eth_hash_*`

File: src/rpc/methods/eth/eth_tx.rs (hunk 6 above)
Comment (hanabi1224) [reply src/rpc/methods/eth/eth_tx.rs:15]: Fixed.

File: src/eth/eip_1559_transaction.rs (hunk 5 above)
Comment (hanabi1224) [reply src/eth/eip_1559_transaction.rs]: Switched to the unbounded API

File: src/eth/eip_1559_transaction.rs (hunk 4 above)
Comment (hanabi1224) [reply src/eth/eip_1559_transaction.rs]: Fixed.

**Review by LesnyRumcajs — APPROVED** [review]
