### PR TITLE
fix(rpc): StateCirculatingSupply

### LINKED ISSUE #4968: fix failing Filecoin.StateCirculatingSupply RPC tests or corresponding endpoint.
# Issue summary
`Filecoin.StateCirculatingSupply` method failed for both normal node and offline node tests in https://github.com/ChainSafe/forest/actions/runs/11690575434/job/32556124074

## Info:

[job-logs.txt.zip](https://github.com/user-attachments/files/17660350/12_Calibnet.RPC.checks.txt.zip)

The offending snapshot is at DO bucket https://forest-snapshots.fra1.cdn.digitaloceanspaces.com/debug/#4968/forest_snapshot_calibnet_2024-11-05_height_2116776.forest.car.zst

The underlying issue might be either incorrect implementation or invalid test assumption. Ideally, the test should still be there, on way or another.

### PR DESCRIPTION
**Pull request by hanabi1224**
## Summary of changes

See #4968

Changes introduced in this pull request:

-

## Reference issue to close (if applicable)

Closes #4968

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation. All new code adheres to the team's [documentation standards](https://github.com/ChainSafe/forest/wiki/Documentation-practices),
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

File: src/rpc/methods/state.rs [hunk 1]
```diff
@@ -1542,7 +1542,8 @@ impl RpcMethod<1> for StateCirculatingSupply {
         let height = ts.epoch();
         let root = ts.parent_state();
         let genesis_info = GenesisInfo::from_chain_config(ctx.chain_config().clone());
-        let supply = genesis_info.get_state_circulating_supply(height, &ctx.store_owned(), root)?;
+        let supply =
+            genesis_info.get_state_circulating_supply(height - 1, &ctx.store_owned(), root)?;
```
Comment (hanabi1224) [inline src/rpc/methods/state.rs:1546]:
```go
func (a *StateAPI) StateCirculatingSupply(ctx context.Context, tsk types.TipSetKey) (abi.TokenAmount, error) {
	ts, err := a.Chain.GetTipSetFromKey(ctx, tsk)
	if err != nil {
		return types.EmptyInt, xerrors.Errorf("loading tipset %s: %w", tsk, err)
	}

	sTree, err := a.StateManager.ParentState(ts)
	if err != nil {
		return types.EmptyInt, err
	}
	return a.StateManager.GetCirculatingSupply(ctx, ts.Height()-1, sTree)
}
```

Comment (elmattic) [reply src/rpc/methods/state.rs:1546]: Nice catch!

**Review by elmattic — APPROVED** [review]

**Review by lemmih — APPROVED** [review]
