### PR TITLE
Copy reqwest_resume code to forest

### LINKED ISSUE #3468: Repeated `503`s when downloading a snapshot
aria2c can handle and resume, but this is going to kill anyone not using aria2c
```console
root@aatifsyed-behind-the-code-xl:~# ./forest-v0.12.1/forest-cli snapshot fetch -d. --vendor forest

09/07 14:18:31 [NOTICE] Downloading 1 item(s)
 *** Download Progress Summary as of Thu Sep  7 14:19:34 2023 ***
=========================================================================================================================
[#3c38ea 26GiB/58GiB(45%) CN:5 DL:418MiB ETA:1m17s]
FILE: ./forest_snapshot_mainnet_2023-09-07_height_3192203.forest.car.zst
-------------------------------------------------------------------------------------------------------------------------

[#3c38ea 54GiB/58GiB(93%) CN:5 DL:535MiB ETA:7s]
09/07 14:20:25 [ERROR] CUID#10 - Download aborted. URI=https://fra1.digitaloceanspaces.com/forest-snapshots/mainnet/forest_snapshot_mainnet_2023-09-07_height_3192203.forest.car.zst
Exception: [AbstractCommand.cc:351] errorCode=29 URI=https://fra1.digitaloceanspaces.com/forest-snapshots/mainnet/forest_snapshot_mainnet_2023-09-07_height_3192203.forest.car.zst
  -> [HttpSkipResponseCommand.cc:231] errorCode=29 The response status is not successful. status=503

09/07 14:20:26 [ERROR] CUID#9 - Download aborted. URI=https://fra1.digitaloceanspaces.com/forest-snapshots/mainnet/forest_snapshot_mainnet_2023-09-07_height_3192203.forest.car.zst
Exception: [AbstractCommand.cc:351] errorCode=29 URI=https://fra1.digitaloceanspaces.com/forest-snapshots/mainnet/forest_snapshot_mainnet_2023-09-07_height_3192203.forest.car.zst
  -> [HttpSkipResponseCommand.cc:231] errorCode=29 The response status is not successful. status=503

09/07 14:20:26 [ERROR] CUID#12 - Download aborted. URI=https://fra1.digitaloceanspaces.com/forest-snapshots/mainnet/forest_snapshot_mainnet_2023-09-07_height_3192203.forest.car.zst
Exception: [AbstractCommand.cc:351] errorCode=29 URI=https://fra1.digitaloceanspaces.com/forest-snapshots/mainnet/forest_snapshot_mainnet_2023-09-07_height_3192203.forest.car.zst
  -> [HttpSkipResponseCommand.cc:231] errorCode=29 The response status is not successful. status=503
 *** Download Progress Summary as of Thu Sep  7 14:20:34 2023 ***
=========================================================================================================================
[#3c38ea 57GiB/58GiB(98%) CN:2 DL:351MiB ETA:2s]
FILE: ./forest_snapshot_mainnet_2023-09-07_height_3192203.forest.car.zst
-------------------------------------------------------------------------------------------------------------------------

[#3c38ea 57GiB/58GiB(99%) CN:2 DL:343MiB ETA:1s]
09/07 14:20:35 [ERROR] CUID#11 - Download aborted. URI=https://fra1.digitaloceanspaces.com/forest-snapshots/mainnet/forest_snapshot_mainnet_2023-09-07_height_3192203.forest.car.zst
Exception: [AbstractCommand.cc:351] errorCode=29 URI=https://fra1.digitaloceanspaces.com/forest-snapshots/mainnet/forest_snapshot_mainnet_2023-09-07_height_3192203.forest.car.zst
  -> [HttpSkipResponseCommand.cc:231] errorCode=29 The response status is not successful. status=503

09/07 14:20:36 [NOTICE] Download complete: ./forest_snapshot_mainnet_2023-09-07_height_3192203.forest.car.zst

Download Results:
gid   |stat|avg speed  |path/URI
======+====+===========+=======================================================
3c38ea|OK  |   476MiB/s|./forest_snapshot_mainnet_2023-09-07_height_3192203.forest.car.zst

Status Legend:
(OK):download completed.
./forest_snapshot_mainnet_2023-09-07_height_3192203.forest.car.zst
```

### PR DESCRIPTION
**Pull request by elmattic**
## Summary of changes

Changes introduced in this pull request:

- Add a copy of `reqwest_resume` crate code to Forest with minimal modifications
- Add two unit tests
- Make use of resumable `get` in our `reader` utility code

This PR addresses the resume part of #3511.

## Reference issue to close (if applicable)

Closes #3468 #3543

## Change checklist

- [x] I have performed a self-review of my own code,
- [x] I have made corresponding changes to the documentation,
- [x] I have added tests that prove my fix is effective or that my feature works (if possible),
- [x] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md

### CODE REVIEW

**Comment by LesnyRumcajs** [comment]
If you copied a significant chunk of the original [reqwest_resume](https://github.com/alecmocatta/reqwest_resume), you should properly attribute the author.

File: src/utils/reqwest_resume/mod.rs [hunk 1]
```diff
@@ -0,0 +1,165 @@
...
+        }
+    }
+}
+
+/// A Response to a submitted Request.
+///
+/// See [`reqwest::Response`].
+#[derive(Debug)]
+pub struct Response {
+    _client: reqwest::Client,
```
Comment (ruseinov) [inline src/utils/reqwest_resume/mod.rs:101]: Any reason for those fields to be `_`?

File: src/utils/reqwest_resume/mod.rs [hunk 2]
```diff
@@ -0,0 +1,165 @@
...
+            }
+        }
+    }
+}
+
+/// Shortcut method to quickly make a GET request.
+///
+/// See [`reqwest::get`].
+pub fn get(url: reqwest::Url) -> impl Future<Output = reqwest::Result<Response>> + Send {
+    // <T: IntoUrl>
```
Comment (ruseinov) [inline src/utils/reqwest_resume/mod.rs:163]: Do we need this comment?

File: src/utils/reqwest_resume/mod.rs [hunk 3]
```diff
@@ -0,0 +1,165 @@
...
+}
+impl Stream for Decoder {
+    type Item = reqwest::Result<Bytes>;
+
+    fn poll_next(mut self: Pin<&mut Self>, cx: &mut Context) -> Poll<Option<Self::Item>> {
+        loop {
+            match ready!(self.decoder.as_mut().poll_next(cx)) {
+                Some(Err(err)) => {
+                    if !self.accept_byte_ranges {
+                        // TODO: we could try, for those servers that don't output Accept-Ranges but work anyway
```
Comment (ruseinov) [inline src/utils/reqwest_resume/mod.rs:131]: TODO should be either removed or replaced with an issue link or a comment.

File: src/utils/reqwest_resume/mod.rs [hunk 4]
```diff
@@ -0,0 +1,165 @@
...
+                        break Poll::Ready(Some(Err(err)));
+                    }
+                    let builder = self.client.request(self.method.clone(), self.url.clone());
+                    let mut headers = HeaderMap::new();
+                    let value = HeaderValue::from_str(&std::format!("bytes={}-", self.pos))
+                        .expect("invalid ASCII string");
```
Comment (ruseinov) [inline src/utils/reqwest_resume/mod.rs:137]: Could be changed to `unreachable`. Since `self.pos` is a `u64` - that should always work.

**Comment by ruseinov** [comment]
This should probably be incorporated into one of the test scripts we have that download things, just to make sure it works properly.

File: src/utils/reqwest_resume/mod.rs (hunk 1 above)
Comment (elmattic) [reply src/utils/reqwest_resume/mod.rs:101]: This was to avoid lint errors (fields are never read). Maybe we could remove them all and return directly a `reqwest::Response`?

File: src/utils/reqwest_resume/mod.rs (hunk 2 above)
Comment (elmattic) [reply src/utils/reqwest_resume/mod.rs:163]: Not really. Keep in mind that most of the code comes from the `reqwest_resume` crate and I did minimal modifications.

File: src/utils/reqwest_resume/mod.rs (hunk 4 above)
Comment (elmattic) [reply src/utils/reqwest_resume/mod.rs:137]: What's the difference compared to a call to `expect`?

**Comment by elmattic** [comment]
> This should probably be incorporated into one of the test scripts we have that download things, just to make sure it works properly.

The scripts that download things already make use of this code. I think what will be more useful is a few unit tests (a follow up issue has been created).

File: src/utils/reqwest_resume/mod.rs (hunk 2 above)
Comment (ruseinov) [reply src/utils/reqwest_resume/mod.rs:162]: I understand that. Let's remove everything that seems redundant, unless there is a good reason not to.

File: src/utils/reqwest_resume/mod.rs (hunk 4 above)
Comment (ruseinov) [reply src/utils/reqwest_resume/mod.rs:136]: I'm just talking about `expect("unreachable")`. I think it's more straightforward than whatever is there now.

File: src/utils/reqwest_resume/mod.rs (hunk 1 above)
Comment (ruseinov) [reply src/utils/reqwest_resume/mod.rs:101]: They are never read, but the whole object is sent within a `Result`. I would consider doing `allow(unused)` or returning an actual `reqwest::Response` if that serves the purpose.

File: src/utils/reqwest_resume/mod.rs (hunk 4 above)
Comment (elmattic) [reply src/utils/reqwest_resume/mod.rs:136]: Ah ok, make sense. I thought you were talking about `unreachable!`.

File: src/utils/reqwest_resume/mod.rs [hunk 5]
```diff
@@ -0,0 +1,164 @@
...
+            }
+        }
+    }
+}
+
+/// Shortcut method to quickly make a GET request.
+///
+/// See [`reqwest::get`].
+pub fn get(url: reqwest::Url) -> impl Future<Output = reqwest::Result<Response>> + Send {
+    // <T: IntoUrl>
```
Comment (ruseinov) [inline src/utils/reqwest_resume/mod.rs:162]:
```suggestion
```

**Comment by LesnyRumcajs** [comment]
I wouldn't add this without any tests. Looking at the PR and the missing summary of changes, I don't know precisely what it does.

**Comment by elmattic** [comment]
> I wouldn't add this without any tests. Looking at the PR and the missing summary of changes, I don't know precisely what it does.

We tried to setup some test environment using `hyper` server, sending a few bytes (and later simulating an error) but this didn't quite work.
We keep getting the `reqwest` error:
```
reqwest::Error {
    kind: Request,
    url: Url {
        scheme: "http",
        cannot_be_a_base: false,
        username: "",
        password: None,
        host: Some(
            Domain(
                "localhost",
            ),
        ),
        port: Some(
            3000,
        ),
        path: "/",
        query: None,
        fragment: None,
    },
    source: hyper::Error(
        IncompleteMessage,
    ),
}
```

File: src/utils/reqwest_resume/mod.rs [hunk 6]
```diff
@@ -0,0 +1,227 @@
...
+        tokio::task::spawn(server);
+
+        let mut resp = get(reqwest::Url::parse("http://localhost:3000").unwrap())
+            .await?
+            .response();
+
+        dbg!(resp.headers());
+        while let Some(data) = resp.chunk().await? {
+            dbg!(format!("chunk len {}", data.len()));
+        }
```
Comment (lemmih) [inline src/utils/reqwest_resume/mod.rs:223]: You'll soon have to use the `Decoder`.

File: src/utils/reqwest_resume/mod.rs (hunk 1 above)
Comment (elmattic) [reply src/utils/reqwest_resume/mod.rs]: The code was actually unused, so that explains why.

File: src/utils/reqwest_resume/mod.rs [hunk 7]
```diff
@@ -0,0 +1,295 @@
...
+        let server = Server::bind(&addr).serve(make_svc);
+
+        println!("Listening on http://{}", addr);
+
+        tokio::task::spawn(server)
+    }
+
+    #[tokio::test]
+    pub async fn test_resumable_get() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
+        let port = 3000;
```
Comment (lemmih) [inline src/utils/reqwest_resume/mod.rs:260]: Let's use a random available port.

File: src/utils/reqwest_resume/mod.rs [hunk 8]
```diff
@@ -0,0 +1,295 @@
...
+
+        let server = Server::bind(&addr).serve(make_svc);
+
+        println!("Listening on http://{}", addr);
+
+        tokio::task::spawn(server)
+    }
+
+    #[tokio::test]
+    pub async fn test_resumable_get() -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
```
Comment (lemmih) [inline src/utils/reqwest_resume/mod.rs:259]: Tests shouldn't return `Result`. Use `unwrap` instead.

File: src/utils/reqwest_resume/mod.rs [hunk 9]
```diff
@@ -0,0 +1,295 @@
...
+        let port = 3000;
+        create_flaky_server(port).await;
+
+        let resp = get(reqwest::Url::parse(&format!("http://localhost:{}", port)).unwrap()).await?;
```
Comment (lemmih) [inline src/utils/reqwest_resume/mod.rs:263]: Will displaying the local addr of the server work here?

File: src/utils/reqwest_resume/mod.rs [hunk 10]
```diff
@@ -0,0 +1,295 @@
...
+        let range = parse_ranges.validate(total_len as u64).unwrap();
+        *range[0].start()
+    }
+
+    async fn hello(req: Request<Body>) -> Result<Response<Body>, Infallible> {
+        let buffer = [b'a'; BUFFER_LEN];
+
+        let body = if let Some(range) = req.headers().get(header::RANGE) {
+            let offset = extract_range_start(range, buffer.len());
+            let (mut sender, body) = Body::channel();
```
Comment (lemmih) [inline src/utils/reqwest_resume/mod.rs:204]: Looks like you can hoist this out.

File: src/utils/reqwest_resume/mod.rs [hunk 11]
```diff
@@ -0,0 +1,295 @@
...
+
+/// Shortcut method to quickly make a GET request.
+///
+/// See [`reqwest::get`].
+pub fn get(url: reqwest::Url) -> impl Future<Output = reqwest::Result<Response>> + Send {
+    Client::new().get(url).send()
+}
+
+#[cfg(test)]
+mod tests {
```
Comment (lemmih) [inline src/utils/reqwest_resume/mod.rs:179]: These tests are quite complicated. Maybe move them to a separate file.

**Review by lemmih — CHANGES_REQUESTED** [review]

File: src/utils/reqwest_resume/mod.rs (hunk 7 above)
Comment (elmattic) [reply src/utils/reqwest_resume/mod.rs:260]: Would using port 0 work? According to the documentation:

> 0 will request that the OS assigns a port to this listener.

https://doc.rust-lang.org/std/net/struct.TcpListener.html#method.bind

Comment (lemmih) [reply src/utils/reqwest_resume/mod.rs:260]: Give it a go.

Comment (elmattic) [reply src/utils/reqwest_resume/mod.rs]: It works like a charm!

File: src/utils/reqwest_resume/mod.rs (hunk 9 above)
Comment (elmattic) [reply src/utils/reqwest_resume/mod.rs]: I've removed the print.

File: src/utils/reqwest_resume/mod.rs [hunk 12]
```diff
@@ -0,0 +1,181 @@
...
```
Comment (lemmih) [inline src/utils/reqwest_resume/mod.rs:179]: This is a rather unusual way of structuring the code. How about just

```rust
[cfg(test)]
mod tests;
```

File: src/utils/reqwest_resume/tests/get_test.rs [hunk 13]
```diff
@@ -0,0 +1,116 @@
...
+use http_range_header::parse_range_header;
+use hyper::header::{self, HeaderValue};
+use hyper::service::{make_service_fn, service_fn};
+use hyper::{Body, Request, Response, Server};
+use std::convert::Infallible;
+use std::time::Duration;
+use tokio::time::sleep;
+
+const BUFFER_LEN: usize = 4096 * 2;
+const CHUNK_LEN: usize = 4096;
```
Comment (lemmih) [inline src/utils/reqwest_resume/tests/get_test.rs:15]: Could you let me know why you picked these values? What are the constraints on sensible values here?

File: src/utils/reqwest_resume/tests/get_test.rs [hunk 14]
```diff
@@ -0,0 +1,116 @@
...
+
+fn extract_range_start(value: &HeaderValue, total_len: usize) -> u64 {
+    let s = std::str::from_utf8(value.as_bytes()).unwrap();
+    let parse_ranges = parse_range_header(s).unwrap();
+    let range = parse_ranges.validate(total_len as u64).unwrap();
+    *range[0].start()
+}
+
+async fn hello(req: Request<Body>) -> Result<Response<Body>, Infallible> {
```
Comment (lemmih) [inline src/utils/reqwest_resume/tests/get_test.rs:24]: Some documentation would be nice here. It looks like you only abort the connection once. How about aborting more than once?

Comment (lemmih) [reply src/utils/reqwest_resume/tests/get_test.rs:24]: Also, I think you can find a better name than `hello`.

File: src/utils/reqwest_resume/tests/get_test.rs [hunk 15]
```diff
@@ -0,0 +1,116 @@
...
+    response
+        .headers_mut()
+        .insert(header::ACCEPT_RANGES, HeaderValue::from_static("bytes"));
+    Ok(response)
+}
+
+async fn create_flaky_server() -> (
+    tokio::task::JoinHandle<std::result::Result<(), hyper::Error>>,
+    std::net::SocketAddr,
+) {
```
Comment (lemmih) [inline src/utils/reqwest_resume/tests/get_test.rs:64]: It looks like you always ignore the returned `JoinHandle`. Why is that?

File: src/utils/reqwest_resume/tests/get_test.rs [hunk 16]
```diff
@@ -0,0 +1,116 @@
...
+    // For every connection, we must make a `Service` to handle all
+    // incoming HTTP requests on said connection.
+
+    let make_svc = make_service_fn(|_conn| {
+        // This is the `Service` that will handle the connection.
+        // `service_fn` is a helper to convert a function that
+        // returns a Response into a `Service`.
```
Comment (lemmih) [inline src/utils/reqwest_resume/tests/get_test.rs:71]: These comments aren't useful in the tests. They're a vestige of the example code you copied.

File: src/utils/reqwest_resume/tests/get_test.rs [hunk 17]
```diff
@@ -0,0 +1,116 @@
...
+
+    let resp = get(reqwest::Url::parse(&format!("http://{addr}")).unwrap())
+        .await
+        .unwrap();
+
+    let mut stream = resp.bytes_stream();
+    let mut read_len = 0;
+    while let Some(item) = stream.next().await {
+        read_len += item.unwrap().len();
+    }
```
Comment (lemmih) [inline src/utils/reqwest_resume/tests/get_test.rs:96]: Could we test that the data is actually as expected as well?

**Review by lemmih — DISMISSED** [review]

File: src/utils/reqwest_resume/tests/get_test.rs (hunk 15 above)
Comment (elmattic) [reply src/utils/reqwest_resume/tests/get_test.rs]: We don't use the handle. Let's not return it from `create_flaky_server` at all, then.

File: src/utils/reqwest_resume/tests/get_test.rs (hunk 13 above)
Comment (elmattic) [reply src/utils/reqwest_resume/tests/get_test.rs]: Those were arbitrarily chosen. We could use something smaller or bigger here.
The only constraint is that `CHUNK_LEN < BUFFER_LEN.`

However, I'm not sure if we can assert on `BUFFER_LEN` in case of non-resumable get test:

`assert_eq!(item.unwrap().len(), CHUNK_LEN);`

Testing this with a chunk value `10000` shows that we get only `8080` in `test_resumable_get.`
A better approach would be to test the actual data transmitted.

File: src/utils/reqwest_resume/tests.rs [hunk 18]
```diff
@@ -0,0 +1,121 @@
...
+        .headers_mut()
+        .insert(header::ACCEPT_RANGES, HeaderValue::from_static("bytes"));
+    Ok(response)
+}
+
+async fn create_flaky_server() -> std::net::SocketAddr {
+    let counter = Arc::new(AtomicUsize::new(0));
+
+    let make_svc = make_service_fn(move |_conn| {
+        let count = counter.fetch_add(1, Ordering::AcqRel);
```
Comment (lemmih) [inline src/utils/reqwest_resume/tests.rs:73]: This is 100% not what you want. You should not have _any_ state in the server.

File: src/utils/reqwest_resume/tests.rs [hunk 19]
```diff
@@ -0,0 +1,113 @@
...
+        .insert(header::ACCEPT_RANGES, HeaderValue::from_static("bytes"));
+    Ok(response)
+}
+
+async fn create_flaky_server() -> std::net::SocketAddr {
+    let make_svc =
+        make_service_fn(|_conn| async { Ok::<_, Infallible>(service_fn(handle_request)) });
+
+    // A port number of 0 will request that the OS assigns a port.
+    let addr = ([127, 0, 0, 1], 0).into();
```
Comment (aatifsyed) [inline src/utils/reqwest_resume/tests.rs:70]: nit: this is always a big magical to me, I'd prefer
```rust
use std::net::{Ipv4Addr, SocketAddr};
SocketAddr::new(Ipv4Addr::LOCALHOST.into(), 0 /* OS-assigned */);
```

File: src/utils/reqwest_resume/tests.rs [hunk 20]
```diff
@@ -0,0 +1,113 @@
...
+
+    tokio::task::spawn(server);
+    addr
+}
+
+#[tokio::test]
+pub async fn test_resumable_get() {
+    let addr = create_flaky_server().await;
+
+    let resp = get(reqwest::Url::parse(&format!("http://{addr}")).unwrap())
```
Comment (aatifsyed) [inline src/utils/reqwest_resume/tests.rs:83]: nit: Odd that this doesn't mirror `reqwest`: https://docs.rs/reqwest/latest/reqwest/trait.IntoUrl.html

**Review by aatifsyed — APPROVED** [review]

File: src/utils/reqwest_resume/tests.rs (hunk 20 above)
Comment (lemmih) [reply src/utils/reqwest_resume/tests.rs:83]: Using `IntoUrl` is super awkward here. It would require significant changes to the code.

File: src/utils/reqwest_resume/tests.rs [hunk 21]
```diff
@@ -0,0 +1,113 @@
...
+    let s = std::str::from_utf8(value.as_bytes()).unwrap();
+    let parse_ranges = parse_range_header(s).unwrap();
+    parse_ranges
+        .validate(RANDOM_BYTES.len() as u64)
+        .map_or(Range::default(), |range| {
+            let start = *range[0].start() as usize;
+            // The increment here is to convert into a `std::ops::Range`
+            // which has an exclusive upper bound.
+            let end = *range[0].end() as usize + 1;
+            start..end
```
[the remark this answers is not in the document]
Comment (lemmih) [reply src/utils/reqwest_resume/tests.rs:31]: Not sure what this comment means. We _have_ a `RangeInclusive`. We _need_ a `Range`. The code is question converts the `RangeInclusive` to a `Range`.

[the remark this answers is not in the document]
Comment (aatifsyed) [reply src/utils/reqwest_resume/tests.rs:32]: Ah, I didn't see that parse_range_header returns `RangeInclusive`

File: src/utils/reqwest_resume/tests.rs [hunk 22]
```diff
@@ -0,0 +1,114 @@
...
+    });
+
+    let mut response: Response<_> = Response::new(body);
+    response
+        .headers_mut()
+        .insert(header::ACCEPT_RANGES, HeaderValue::from_static("bytes"));
+    Ok(response)
+}
+
+async fn create_flaky_server() -> std::net::SocketAddr {
```
Comment (aatifsyed) [inline src/utils/reqwest_resume/tests.rs:66]:
```suggestion
async fn create_flaky_server() -> SocketAddr {
```
No longer needs to be fully qualified

File: src/utils/reqwest_resume/tests.rs [hunk 23]
```diff
@@ -0,0 +1,114 @@
...
+
+    let server = Server::bind(&addr).serve(make_svc);
+    let addr = server.local_addr();
+
+    tokio::task::spawn(server);
+    addr
+}
+
+#[tokio::test]
+pub async fn test_resumable_get() {
```
Comment (aatifsyed) [inline src/utils/reqwest_resume/tests.rs:81]:
```suggestion
async fn test_resumable_get() {
```

File: src/utils/reqwest_resume/tests.rs [hunk 24]
```diff
@@ -0,0 +1,114 @@
...
+        .bytes_stream()
+        .map(|item| item.unwrap())
+        .collect::<Vec<Bytes>>()
+        .await
+        .concat();
+    assert_eq!(Bytes::from_static(&RANDOM_BYTES), data);
+}
+
+#[tokio::test]
+pub async fn test_non_resumable_get() {
```
Comment (aatifsyed) [inline src/utils/reqwest_resume/tests.rs:98]:
```suggestion
async fn test_non_resumable_get() {
```

File: src/utils/reqwest_resume/mod.rs [hunk 25]
```diff
@@ -0,0 +1,179 @@
...
+    ///
+    /// See [`reqwest::Client::new()`].
+    pub fn new() -> Self {
+        Self(reqwest::Client::new())
+    }
+    /// Convenience method to make a `GET` request to a URL.
+    ///
+    /// See [`reqwest::Client::get()`].
+    pub fn get(&self, url: reqwest::Url) -> RequestBuilder {
+        // <U: reqwest::IntoUrl>
```
Comment (aatifsyed) [inline src/utils/reqwest_resume/mod.rs:51]:
```suggestion
```

File: src/utils/reqwest_resume/mod.rs [hunk 26]
```diff
@@ -0,0 +1,179 @@
...
+/// A builder to construct the properties of a Request.
+///
+/// See [`reqwest::RequestBuilder`].
+#[derive(Debug)]
+pub struct RequestBuilder(reqwest::Client, reqwest::Method, reqwest::Url);
+impl RequestBuilder {
+    /// Constructs the Request and sends it the target URL, returning a Response.
+    ///
+    /// See [`reqwest::RequestBuilder::send()`].
+    pub fn send(&mut self) -> impl Future<Output = reqwest::Result<Response>> + Send {
```
Comment (aatifsyed) [inline src/utils/reqwest_resume/mod.rs:65]: Why is this not `async fn` instead of `fn -> impl Future`?

File: src/utils/reqwest_resume/mod.rs [hunk 27]
```diff
@@ -0,0 +1,179 @@
...
+
+//! Wrapper that uses the `Range` HTTP header to resume get requests.
+//!
+//! Most of the code can be attributed to `Alec Mocatta` and comes from the crate
+//! <https://crates.io/crates/reqwest_resume/>
+//! Some modifications have been done to update the code regarding `tokio`,
+//! replace the `hyperx` dependency with `hyper` and add two unit tests.
+
+use bytes::Bytes;
+use futures::{ready, FutureExt, Stream, TryFutureExt};
```
Comment (aatifsyed) [inline src/utils/reqwest_resume/mod.rs:14]:
```suggestion
use futures::{ready, FutureExt as _, Stream, TryFutureExt as _};
```

Comment (aatifsyed) [reply src/utils/reqwest_resume/mod.rs:14]: extension traits should never need to be named

File: src/utils/reqwest_resume/mod.rs [hunk 28]
```diff
@@ -0,0 +1,179 @@
...
+                None => break Poll::Ready(None),
+            }
+        }
+    }
+}
+
+/// Shortcut method to quickly make a GET request.
+///
+/// See [`reqwest::get`].
+pub fn get(url: reqwest::Url) -> impl Future<Output = reqwest::Result<Response>> + Send {
```
Comment (aatifsyed) [inline src/utils/reqwest_resume/mod.rs:174]: as above with `async fn`

File: src/utils/reqwest_resume/mod.rs [hunk 29]
```diff
@@ -0,0 +1,179 @@
...
+                    headers.insert(header::RANGE, value);
+                    let builder = builder.headers(headers);
+                    // https://developer.mozilla.org/en-US/docs/Web/HTTP/Range_requests
+                    // https://github.com/sdroege/gst-plugin-rs/blob/dcb36832329fde0113a41b80ebdb5efd28ead68d/gst-plugin-http/src/httpsrc.rs
+                    self.decoder = Box::pin(
+                        Box::pin(sleep(Duration::from_secs(1)))
+                            .then(|()| builder.send())
+                            .map_ok(reqwest::Response::bytes_stream)
+                            .try_flatten_stream(),
+                    );
```
[the remark this answers is not in the document]
Comment (lemmih) [reply src/utils/reqwest_resume/mod.rs]: It was required by the `Unpin` constraint in the `Decoder`. I removed the constraint.

File: src/utils/reqwest_resume/mod.rs (hunk 26 above)
Comment (lemmih) [reply src/utils/reqwest_resume/mod.rs]: Fixed.
