### PR TITLE
Rpc fixes and implementations

### LINKED ISSUE #800: MinerGetBaseInfo needed for Storage Miner
**Issue summary**
In order to initialize storage miner, MinerGetBaseInfo should be implemented.

**Other information and links**
https://github.com/filecoin-project/lotus/blob/master/api/api_full.go#L234

### LINKED ISSUE #830: Add GetNtwkVersion to State Manager
**Issue summary**

Implement a function to get network version based on the epoch in the State Manager. 

[See Lotus implementation](https://github.com/filecoin-project/lotus/blob/efd2dff0cac40934ec5b4472e48887ecbb2efe44/chain/stmgr/stmgr.go#L1140)

[We have this implemented in Forest already](https://github.com/ChainSafe/forest/blob/0b7a49b6ac3879ecea953c487218a994a91c14f7/types/src/version.rs#L66)

**Other information and links**

### PR DESCRIPTION
**Pull request by AshantiMutinta**
**Summary of changes**
Changes introduced in this pull request:
- This implements various fixes for the rpc layer

**Reference issue to close (if applicable)**

Closes #830 
Closes #800 

**Other information and links**

### CODE REVIEW

File: vm/actor/src/builtin/miner/state.rs [hunk 1]
```diff
@@ -1024,7 +1138,25 @@ mod tests {
...
+            pending_worker_key: None,
+            peer_id: PeerId::random().into_bytes(),
+            multi_address: vec![BytesDe(PeerId::random().into_bytes())],
+            sector_size: SectorSize::_2KiB,
+            seal_proof_type: RegisteredSealProof::from(1),
+            window_post_partition_sectors: 0,
+        };
+        let val = serde_json::to_string(&info);
+        println!("miner info {:?}", val);
+    }
```
Comment (austinabell) [inline vm/actor/src/builtin/miner/state.rs:1161]: This test doesn't do anything, consider asserting the format? (You also shouldn't need the debug print for this)

File: vm/address/src/lib.rs [hunk 2]
```diff
@@ -359,4 +359,92 @@ pub mod json {
...
+        use std::borrow::Cow;
+
+        pub fn serialize<S>(v: &Option<Address>, serializer: S) -> Result<S::Ok, S::Error>
+        where
+            S: Serializer,
+        {
+            if let Some(unwrapped_address) = v.as_ref() {
+                serializer.serialize_str(&encode(unwrapped_address))
+            } else {
+                serializer.serialize_str("\u{003c}\u{0065}\u{006d}\u{0070}\u{0074}\u{0079}\u{003e}")
```
Comment (austinabell) [inline vm/address/src/lib.rs:411]: wait, what is this?

File: vm/actor/src/builtin/miner/state.rs [hunk 3]
```diff
@@ -1005,6 +1025,100 @@ impl MinerInfo {
...
+    pub struct MinerInfoJson {
+        pub owner: AddressJson,
+
+        pub worker: AddressJson,
+
+        #[serde(with = "address::json::opt")]
+        pub new_worker: Option<Address>,
+
+        #[serde(with = "address::json::opt_vec")]
+        pub control_addresses: Option<Vec<Address>>, // Must all be ID addresses.
```
Comment (austinabell) [inline vm/actor/src/builtin/miner/state.rs:1068]: This should just be a vec?

File: vm/actor/src/builtin/miner/state.rs [hunk 4]
```diff
@@ -1005,6 +1025,100 @@ impl MinerInfo {
...
+
+        pub worker_change_epoch: ChainEpoch,
+
+        /// Optional worker key to update at an epoch
+        pub pending_worker_key: Option<WorkerKeyChange>,
```
Comment (austinabell) [inline vm/actor/src/builtin/miner/state.rs:1073]: You shouldn't need to document or expose the fields? Or is there an issue with that?

File: vm/address/src/lib.rs [hunk 5]
```diff
@@ -359,4 +359,92 @@ pub mod json {
...
+                let mut seq = serializer.serialize_seq(Some(unwrapped_addresses.len()))?;
+                for e in unwrapped_addresses {
+                    seq.serialize_element(&AddressJsonRef(e))?;
+                }
+                seq.end()
+            } else {
+                serializer.serialize_none()
+            }
+        }
+    }
```
Comment (austinabell) [inline vm/address/src/lib.rs:449]: This should never be necessary, best not to fall into this pattern of wrapping empty vecs in an `Option`

File: blockchain/beacon/src/drand.rs [hunk 6]
```diff
@@ -34,6 +35,40 @@ impl DrandPublic {
     }
 }
 
+pub struct Schedule<T>(pub Vec<BeaconPoint<T>>)
+where
+    T: Beacon;
```
Comment (austinabell) [inline blockchain/beacon/src/drand.rs:40]: you shouldn't need to constrain T here

File: blockchain/beacon/src/drand.rs [hunk 7]
```diff
@@ -34,6 +35,40 @@ impl DrandPublic {
...
+            .map(|s| &s.beacon)
+        {
+            Ok(&*beacon_point)
+        } else {
+            self.0
+                .first()
+                .map(|s| &*s.beacon)
+                .ok_or_else(|| Box::from("Could not get first_value of beacon in beacon_for_epoch"))
+        }
+    }
```
Comment (austinabell) [inline blockchain/beacon/src/drand.rs:61]: Should maybe use shared logic as in `types::version` or connect it in some way so we don't have two similar functionalities not connected?

File: blockchain/chain/src/store/chain_store.rs [hunk 8]
```diff
@@ -534,6 +534,91 @@ where
...
+        .map(|(header, (bls_messages, secp_messages))| Block {
+            header,
+            bls_messages,
+            secp_messages,
+        })
+        .collect();
+
+    // the given tipset has already been verified, so this cannot fail
+    Ok(FullTipset::new(blocks).unwrap())
+}
```
Comment (austinabell) [inline blockchain/chain/src/store/chain_store.rs:588]:
```suggestion
```
No need to reintroduce this

File: blockchain/chain/src/store/chain_store.rs [hunk 9]
```diff
@@ -610,6 +695,87 @@ pub fn draw_randomness(
...
+                return Ok(Some(pts));
+            }
+            return Ok(ts_temp);
+        }
+        if height == pts.epoch() {
+            return Ok(Some(pts));
+        }
+        ts_temp = Some(pts);
+    }
+}
```
Comment (austinabell) [inline blockchain/chain/src/store/chain_store.rs:777]: please revert this as well, shouldn't have a regression in this (there are the functions attached to `ChainStore` you can use

File: blockchain/chain/src/store/chain_store.rs [hunk 10]
```diff
@@ -534,6 +534,91 @@ where
...
+    address: &Address,
+    tsk: &TipsetKeys,
+) -> Result<miner::State, Error>
+where
+    DB: BlockStore,
+{
+    let state = parent_state_tsk(db, tsk)?;
+    let actor = state
+        .get_actor(address)
+        .map_err(|_| Error::Other("Failure getting actor".to_string()))?
```
Comment (austinabell) [inline blockchain/chain/src/store/chain_store.rs:602]: why ignore the underlying error?

File: blockchain/chain/src/store/chain_store.rs [hunk 11]
```diff
@@ -534,6 +534,91 @@ where
...
+    Ok(act)
+}
+
+fn parent_state_tsk<'a, DB>(db: &'a DB, key: &TipsetKeys) -> Result<StateTree<'a, DB>, Error>
+where
+    DB: BlockStore,
+{
+    let ts = tipset_from_keys(db, key)?;
+    StateTree::new_from_root(db, ts.parent_state())
+        .map_err(|_| Error::Other("Could not get actor state".to_string()))
```
Comment (austinabell) [inline blockchain/chain/src/store/chain_store.rs:619]: same here, use `format!` or something

**Review by austinabell — CHANGES_REQUESTED** [review]

File: vm/address/src/lib.rs (hunk 2 above)
Comment (AshantiMutinta) [reply vm/address/src/lib.rs:411]: This serializes the empty address. If you look at the NewWorker in lotus it should be expecting "\u003cempty\u003e"

File: vm/actor/src/builtin/miner/state.rs (hunk 3 above)
Comment (AshantiMutinta) [reply vm/actor/src/builtin/miner/state.rs:1068]: Vec will still serialize to [] need to serialize it to nil

File: blockchain/beacon/src/drand.rs (hunk 6 above)
Comment (AshantiMutinta) [reply blockchain/beacon/src/drand.rs:40]: Just following lotus implementing in which the beacon can be switched around. Since it is all at compile time, don't see the issue but will change

File: vm/actor/src/builtin/miner/state.rs (hunk 3 above)
Comment (austinabell) [reply vm/actor/src/builtin/miner/state.rs:1068]: Why? The go implementation should be able to deserialize the empty array the same as nil

File: vm/address/src/lib.rs (hunk 5 above)
Comment (AshantiMutinta) [reply vm/address/src/lib.rs:449]: This is the difference between serialization of an empty vec that returns nil verses an empty vec that serializes an empty set. An empty optional vec will serialize as nil while an empty vec will serialize as [] https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=ed7ce53123d1bc5418b3bb69bda0c8b2

this is matching the data packets that lotus is expecting, had it as a vector before but found failure

File: blockchain/chain/src/store/chain_store.rs (hunk 8 above)
Comment (AshantiMutinta) [reply blockchain/chain/src/store/chain_store.rs:588]: Probably an issue with the merge

File: vm/address/src/lib.rs (hunk 5 above)
Comment (austinabell) [reply vm/address/src/lib.rs:449]: I understand that is what Lotus provides to it's miner, my point is that the Lotus miner will parse the empty array the same as nil, and then we don't have to follow this bad pattern of ambiguous formats and handling the `None` case

File: blockchain/beacon/src/drand.rs (hunk 6 above)
Comment (austinabell) [reply blockchain/beacon/src/drand.rs:40]: Yeah, you just don't need to constrain it _there_. It should be constrained only on the implementation that requires it

File: vm/actor/src/builtin/miner/state.rs (hunk 3 above)
Comment (AshantiMutinta) [reply vm/actor/src/builtin/miner/state.rs:1068]: This is the issue I came across when running it against the miner

File: vm/address/src/lib.rs (hunk 5 above)
Comment (AshantiMutinta) [reply vm/address/src/lib.rs:449]: Okay,I had issues running an empty array but I will switch it to a vector

File: vm/address/src/lib.rs (hunk 2 above)
Comment (austinabell) [reply vm/address/src/lib.rs:411]: so can you at least switch this for `<empty>` instead of the codes?

File: vm/address/src/lib.rs (hunk 5 above)
Comment (austinabell) [reply vm/address/src/lib.rs:449]: I'm not saying that's absolutely the case, but there is other instances that had been tested and assume that the go implementation deserializes it as such. Are you sure, or can you reproduce this with this difference? I don't want to handle this pattern for every single vector just to match the go daemon implementation's json output, if it's functionally the same

File: key_management/src/keystore.rs [hunk 12]
```diff
@@ -84,13 +90,15 @@ pub mod json {
...
         let JsonHelper {
             sig_type,
             private_key,
         } = Deserialize::deserialize(deserializer)?;
+        println!("deserialize key info");
         Ok(KeyInfo {
-            key_type: sig_type,
-            private_key: base64::decode(private_key).map_err(de::Error::custom)?,
+            key_type: sig_type.0,
+            private_key: base64::decode(private_key).unwrap(),
```
Comment (austinabell) [inline key_management/src/keystore.rs:101]: why'd you swap handling to unwrap?

File: key_management/src/keystore.rs [hunk 13]
```diff
@@ -84,13 +90,15 @@ pub mod json {
     where
         D: Deserializer<'de>,
     {
+        println!("deserialize json helper");
         let JsonHelper {
             sig_type,
             private_key,
         } = Deserialize::deserialize(deserializer)?;
+        println!("deserialize key info");
```
Comment (austinabell) [inline key_management/src/keystore.rs:98]:
```suggestion
        let JsonHelper {
            sig_type,
            private_key,
        } = Deserialize::deserialize(deserializer)?;
```

File: key_management/src/wallet.rs [hunk 14]
```diff
@@ -176,6 +176,21 @@ pub fn find_key<T: KeyStore>(addr: &Address, keystore: &T) -> Result<Key, Error>
     Ok(new_key)
 }
 
+pub fn try_find<T: KeyStore>(addr: &Address, keystore: &mut T) -> Result<KeyInfo, Error> {
+    let key_string = format!("wallet-{}", addr.to_string());
+    match keystore.get(&key_string) {
+        Ok(k) => Ok(k),
+        Err(_) => {
+            let mut new_addr = addr.to_string();
+            new_addr.replace_range(0..1, "t");
```
Comment (austinabell) [inline key_management/src/wallet.rs:185]: Can you add some sort of todo to replace the network prefix default in address, or change this with it? Whenever that is changed, this would be a very tricky workaround to debug?

File: vm/address/src/lib.rs (hunk 5 above)
Comment (austinabell) [reply vm/address/src/lib.rs:449]: this can still be removed

File: node/rpc/src/wallet_api.rs [hunk 15]
```diff
@@ -182,40 +196,55 @@ where
...
+        }
+    };
 
     let sig = wallet::sign(
         *key.key_info.key_type(),
         key.key_info.private_key(),
         msg.as_slice(),
     )?;
-
+    println!("sig");
```
Comment (austinabell) [inline node/rpc/src/wallet_api.rs:235]:
```suggestion
```

File: vm/actor/src/builtin/miner/state.rs [hunk 16]
```diff
@@ -1064,6 +1163,7 @@ mod tests {
             seal_proof_type: RegisteredSealProof::from(1),
             window_post_partition_sectors: 0,
         };
+        println!("miner info {:?}", &info);
```
Comment (austinabell) [inline vm/actor/src/builtin/miner/state.rs:1166]:
```suggestion
```

File: crypto/src/signature.rs [hunk 17]
```diff
@@ -343,4 +343,46 @@ pub mod json {
...
+        }
+
+        pub fn deserialize<'de, D>(deserializer: D) -> Result<SignatureType, D::Error>
+        where
+            D: Deserializer<'de>,
+        {
+            println!("deserializer");
+            let json_enum: JsonHelperEnum = Deserialize::deserialize(deserializer)?;
+
+            println!("deserializer json {:?}", &json_enum);
```
Comment (austinabell) [inline crypto/src/signature.rs:380]:
```suggestion
            let json_enum: JsonHelperEnum = Deserialize::deserialize(deserializer)?;
```

File: blockchain/state_manager/src/lib.rs [hunk 18]
```diff
@@ -471,6 +486,211 @@ where
...
+        schedule: &Schedule<B>,
+        key: &TipsetKeys,
+        round: ChainEpoch,
+        address: Address,
+    ) -> Result<Option<MinerBaseInfo>, Box<dyn StdError>> {
+        let tipset = self.cs.tipset_from_keys(key).await?;
+        let prev = match self.cs.latest_beacon_entry(&tipset).await {
+            Ok(prev) => prev,
+            Err(err) => {
+                if std::env::var("LOTUS_IGNORE_DRAND")
```
Comment (austinabell) [inline blockchain/state_manager/src/lib.rs:636]: our equivalent is just `IGNORE_DRAND` and is a constant you can reference

File: blockchain/state_manager/src/lib.rs [hunk 19]
```diff
@@ -471,6 +486,211 @@ where
...
+        V: ProofVerifier,
+    {
+        let mut lbr: ChainEpoch = ChainEpoch::from(0);
+        let version = self
+            .network_versions
+            .iter()
+            .find(|s| round == s.at_or_below)
+            .map(|s| s.network_version)
+            .unwrap_or(self.latest_version);
+        let lb = if version as u8 <= 3 {
```
Comment (austinabell) [inline blockchain/state_manager/src/lib.rs:504]: Ideal to compare against version type, not as u8

**Review by austinabell — CHANGES_REQUESTED** [review]

File: blockchain/beacon/src/drand.rs (hunk 7 above)
Comment (ec2) [reply blockchain/beacon/src/drand.rs:61]: I dont see how this is connected to anything in types::version...

Comment (austinabell) [reply blockchain/beacon/src/drand.rs:61]: ah my bad, was a misread on my part

File: crypto/src/signature.rs [hunk 20]
```diff
@@ -343,4 +343,44 @@ pub mod json {
...
+        {
+            let json_enum: JsonHelperEnum = Deserialize::deserialize(deserializer)?;
+
+            let signature_type = match json_enum {
+                JsonHelperEnum::Bls => SignatureType::BLS,
+                JsonHelperEnum::Secp256k1 => SignatureType::Secp256k1,
+            };
+            Ok(signature_type)
+        }
+    }
```
Comment (austinabell) [inline crypto/src/signature.rs:385]: Is there really an inconsistency in signature json representations? It is serialized as an integer inside of Signature json (is this wrong and we can just make this the default serialization impl of SignatureType?)

File: types/src/version.rs [hunk 21]
```diff
@@ -42,30 +47,42 @@ const MAINNET_SCHEDULE: [Upgrade; 5] = [
...
     },
+    Upgrade {
+        height: UPGRADE_KUMQUAT_HEIGHT,
+        network: NetworkVersion::V6,
+    },
 ];
 
 /// Specifies the network version
-#[derive(Debug, PartialEq, Clone, Copy, PartialOrd)]
+#[derive(Debug, PartialEq, Clone, Copy, PartialOrd, Serialize)]
```
Comment (austinabell) [inline types/src/version.rs:57]: Should this be serialize repr? what is this needed for?

File: vm/address/src/lib.rs [hunk 22]
```diff
@@ -359,4 +359,70 @@ pub mod json {
...
+                serializer.serialize_str("\u{003c}\u{0065}\u{006d}\u{0070}\u{0074}\u{0079}\u{003e}")
+            }
+        }
+
+        pub fn deserialize<'de, D>(deserializer: D) -> Result<Option<Address>, D::Error>
+        where
+            D: Deserializer<'de>,
+        {
+            let address_as_string: Cow<'de, str> = Deserialize::deserialize(deserializer)?;
+            if address_as_string == "\u{003c}\u{0065}\u{006d}\u{0070}\u{0074}\u{0079}\u{003e}" {
```
Comment (austinabell) [inline vm/address/src/lib.rs:420]: putting note to also change this to same as above

**Review by austinabell — CHANGES_REQUESTED** [review]

**Comment by austinabell** [comment]
I just added a bunch of notes to index the things that should be looked into, @ec2 let me know which (if any) you'd like me to update. I don't want to step on your toes with the changes you're doing

File: blockchain/chain_sync/src/sync_worker.rs [hunk 23]
```diff
@@ -445,8 +445,8 @@ where
             .map_err(|e| (*block_cid, e.into()))?;
 
         // Retrieve lookback tipset for validation.
-        let lbts = cs
-            .get_lookback_tipset_for_round(base_ts.clone(), block.header().epoch())
+        let (lbts, _) = sm
```
Comment (austinabell) [inline blockchain/chain_sync/src/sync_worker.rs:448]: can get rid of the tipset state retrieval below if you just get it from here (Tipset state isn't calculated twice, but can still avoid the atomic access through mutex)

File: crypto/src/signature.rs (hunk 20 above)
Comment (ec2) [reply crypto/src/signature.rs:385]: Yeah, it is serialized in json as `bls` or `secp256k1`. Ill make it the default.

Comment (ec2) [reply crypto/src/signature.rs:385]: Lol nvm, i just double checked, there is an inconsistancy. In the wallet rpc, they'll serialize the signature type as `bls` or as `secp256k1`, but in the blockheader for example, they'll use 1 or 2... So i think it is fine to leave this as is

File: types/src/version.rs (hunk 21 above)
Comment (ec2) [reply types/src/version.rs:57]: looks like this should indeed be serialize_repr

File: crypto/src/signature.rs (hunk 20 above)
Comment (austinabell) [reply crypto/src/signature.rs:385]: so weird hahahah

Comment (ec2) [reply crypto/src/signature.rs:385]: Probably one of the lesser weird things xD

File: types/src/version.rs [hunk 24]
```diff
@@ -42,30 +47,42 @@ const MAINNET_SCHEDULE: [Upgrade; 5] = [
...
     /// actors v2 (specs-actors v2.0.x)
-    V4,
+    V4 = 4,
     /// tape (increases max prove commit size by 10x)
-    V5,
-    /// kumquat (specs-actors v2.2.0)
-    V6,
+    V5 = 5,
+    // kumquat   (specs-actors v2.2.0)
+    V6 = 6,
```
Comment (austinabell) [inline types/src/version.rs:73]: none of the integers matter, but if it is to be added, should also add to V7 (these values are already implied though)

**Review by austinabell — APPROVED** [review]
take approval with grain of salt because I was last to push to this branch

**Comment by ec2** [comment]
> take approval with grain of salt because I was last to push to this branch

Your changes LGTM
