### PR TITLE
laudiacay/actors review f17

### LINKED ISSUE #1281: F17: Incorrect error handling in miner::dispute_windowed_post

### PR DESCRIPTION
**Pull request by laudiacay**
**Summary of changes**
Changes introduced in this pull request:
- changing type of verify-post-proof everywhere so it reflects whether it failed verification or failed to verify (actors audit f17)

**Reference issue to close (if applicable)**

Closes #1281 

**Other information and links**

### CODE REVIEW

File: types/src/verifier/mod.rs [hunk 1]
```diff
@@ -176,10 +177,9 @@ pub trait ProofVerifier {
         let prover_id = prover_id_from_u64(prover);
 
         // Verify Proof
-        if !post::verify_window_post(&bytes_32(&randomness), &proofs, &replicas, prover_id)? {
-            Err("Window post was invalid".into())
-        } else {
-            Ok(())
+        match post::verify_window_post(&bytes_32(&randomness), &proofs, &replicas, prover_id) {
```
Comment (elmattic) [inline types/src/verifier/mod.rs:180]: If you only want to transform `Err` case and leave the `Ok` case untouched you can use:
```
post::verify_window_post(&bytes_32(&randomness), &proofs, &replicas, prover_id)
    .map_err(|err| err.into())
```

**Review by elmattic — COMMENTED** [review]
looks good to me

**Review by elmattic — APPROVED** [review]

**Review by elmattic — APPROVED** [review]
