### PR TITLE
Fix resolve_to_key in message pool to be reorg stable 

### LINKED ISSUE #6891: `resolve_to_key` in message pool should resolve at finality for reorg-safety
Lotus resolves to deterministic address at finality to guarantee the ID→key mapping is reorg-stable. We currently resolve against the tipset's parent state, which is safe but does not provide the same reorg-safety guarantee.

https://github.com/ChainSafe/forest/blob/6fab16d5bc799cdedea9c3cc692e8357c1d04e5d/src/message_pool/msgpool/provider.rs#L109-L115

See https://github.com/filecoin-project/lotus/blob/006da4c7e1c1c29ac02b32112c0d205e4085ba35/chain/stmgr/stmgr.go#L347

### PR DESCRIPTION
**Pull request by sudo-shashank**
## Summary of changes

Changes introduced in this pull request:

- Resolve to deterministic address at finality, to ensure the resolved address is reorg-stable. 

## Reference issue to close (if applicable)

Closes #6891 

## Change checklist

- [X] I have performed a self-review of my own code,
- [X] I have made corresponding changes to the documentation. All new code adheres to the team's [documentation standards](https://github.com/ChainSafe/forest/wiki/Documentation-practices),
- [X] I have added tests that prove my fix is effective or that my feature works (if possible),
- [X] I have made sure the [CHANGELOG][1] is up-to-date. All user-facing changes should be reflected in this document.

### Outside contributions

- [ ] I have read and agree to the [CONTRIBUTING][2] document.
- [ ] I have read and agree to the [AI Policy][3] document. I understand that failure to comply with the guidelines will lead to rejection of the pull request.

[1]: https://github.com/ChainSafe/forest/blob/main/CHANGELOG.md
[2]: https://github.com/ChainSafe/forest/blob/main/CONTRIBUTING.md
[3]: https://github.com/ChainSafe/forest/blob/main/AI_POLICY.md

## Release Notes

* **Bug Fixes**
  * Updated address resolution to respect chain finality window; addresses beyond the finality lookback window are now properly validated.

* **Tests**
  * Added test coverage for address resolution with finality lookback behavior.

### CODE REVIEW

File: src/message_pool/msgpool/msg_pool.rs [hunk 1]
```diff
@@ -1107,8 +1114,6 @@ mod tests {
 
     #[test]
     fn test_get_sequence_works_with_both_address_forms() {
-        use crate::message_pool::provider::Provider;
-
         let api = TestApi::default();
         let bls_sig_cache = SizeTrackingLruCache::new_mocked();
         let key_cache = SizeTrackingLruCache::new_mocked();
```
Comment (hanabi1224) [inline src/message_pool/msgpool/msg_pool.rs:1119]: I added a similar cache to state manager in https://github.com/ChainSafe/forest/pull/6928 we should consolidate them. @coderabbitai create a tracking issue.

File: src/message_pool/msgpool/provider.rs [hunk 2]
```diff
@@ -101,13 +102,35 @@ impl<DB: Blockstore> Provider for ChainStore<DB> {
...
+        match addr.protocol() {
+            BLS | Secp256k1 | Delegated => Ok(*addr),
+            Actor => Err(Error::Other(
+                "Cannot resolve actor address to key address".into(),
+            )),
+            _ => {
+                let lookback_ts = if ts.epoch() > self.chain_config().policy.chain_finality {
+                    self.chain_index()
+                        .tipset_by_height(
+                            ts.epoch() - self.chain_config().policy.chain_finality,
```
Comment (hanabi1224) [inline src/message_pool/msgpool/provider.rs:117]: What if `ts` is at a finalized epoch already?

Comment (sudo-shashank) [reply src/message_pool/msgpool/provider.rs:117]: `resolve_to_key` at a finalized `ts` returns the state at `ts.epoch() - policy.chain_finality`

Comment (hanabi1224) [reply src/message_pool/msgpool/provider.rs:118]: Is that expected? If there's an address that became available right at ts.epoch which has been finalized on the chain, using state at `ts.epoch() - policy.chain_finality` resolves to nothing

Comment (sudo-shashank) [reply src/message_pool/msgpool/provider.rs:118]: Yes, this is taken from lotus 

https://github.com/filecoin-project/lotus/blob/7db670848518732139425d36f8baaad7518e569a/chain/stmgr/stmgr.go#L361-L366

**Review by hanabi1224 — APPROVED** [review]
